fix: ModalBottomSheet을 수정한다
pedaling/class101-ui pull request #104
Opened 2019-09-03 12:56 UTC by chiabi

- min-content사용은 사파리에서 예상치 못한 찐빠를 낸다
- 불필요한 Modal 컴포넌트를 삭제한다

2019-09-03 12:57 UTC, ddalpange approved these changes

2019-09-03 13:05 UTC, bae-unidev requested changes

2019-09-03 13:05 UTC, bae-unidev commented on src/overlays/ModalBottomSheet/index.tsx
> +    padding: 24px;
iOS iPhoneX 노치 대응하려면 
`padding-bottom: calc(env(safe-area-inset-bottom));`같은 걸 쓰면 됨! 
지금 다른 모바일에서도 하단 패딩이 커보이는데 이걸로 수정하면 좋을듯!

2019-09-04 02:37 UTC, bae-unidev approved these changes

2019-09-04 02:37 UTC, merged