[WIP] feat: intent에 따른 message는 FormGroup 컴포넌트에서 보여주도록 한다
pedaling/class101-ui pull request #124
Opened 2019-10-01 13:24 UTC by chiabi

- formInput 컴포넌트들에 중복되는 message를 제거하고 intent상태만 관리하도록 한다. message와 message의 intent는 FormGroup컴포넌트에서 사용하도록 한다.
- formInput 컴포넌트 중 disabled 상태 스타일링이 없거나 cursor:now-allowed가 적용되어 있지 않는 부분을 수정한다.
- FormGroup 컴포넌트에 helperText를 추가한다
- FormGroup, formInputs의 변경사항에 대한 문서를 추가한다

2019-10-02 11:07 UTC, bae-unidev requested changes

2019-10-02 11:07 UTC, bae-unidev commented on src/core/GlobalStyle/index.tsx
> +  h1,h2,h3,h4,h5,h6 {
이거 왠지 우리 웹에 적용되면 스타일 깨질것 같은데??

2019-10-02 11:07 UTC, bae-unidev commented on src/core/common/intent.ts
> +import classNames from 'classnames';
우리가 언제부터 classNames을 쓰기 시작했지?

styled-components로 합칠수 있으니 합치자!

2019-10-02 11:07 UTC, bae-unidev commented on src/formControls/FormGroup/index.tsx
> +        <Label color={labelColor || gray800} htmlFor={htmlLabelFor} shouldAlignLabel={isHorizontal && hasHelperText}>
`labelColor || gray800`는 defaultProps로 처리하자~

2019-10-02 11:07 UTC, bae-unidev commented on src/formInputs/Checkbox/index.tsx
> +          {...inputRef && {
이거 React.forwardRef로 구현해줘~

2019-10-02 11:07 UTC, bae-unidev commented on src/formInputs/DatePicker/index.tsx
>    private handleClickDecreaseBtn = () => {
우리가 언제부터 약어를 썼지?

2019-10-02 11:07 UTC, bae-unidev commented on src/formInputs/Input/index.tsx
> +          ref: inputRef,
forwardRef ㄲ

2019-10-02 11:07 UTC, bae-unidev commented on src/formInputs/Select/index.tsx
> +        fill={`${fill}`}
```suggestion
        fill={fill}
```

2019-10-08 06:49 UTC, chiabi commented on src/formInputs/Select/index.tsx
> +        fill={`${fill}`}
이거는 
`Warning: Received `true` for non-boolean attribute` 때문에 적용한 거

https://github.com/styled-components/styled-components/issues/1198

2019-10-08 10:23 UTC, bae-unidev approved these changes

2019-10-08 11:02 UTC, ddalpange requested changes

2019-10-08 11:02 UTC, ddalpange commented on docs/formInputs/TagInput.mdx
> +          value: ['01082210886','01082230886', '01082210886', '01082210886','01082210886','01082210886', '01082210886', '01082210886','01082210886','01082210886', '01082210886', '01082210886','010822
선생님 이거 제 개인정보거든요.
Lorem Ipsum으로 바꿔주세요.

2019-10-08 11:25 UTC, chiabi commented on docs/formInputs/TagInput.mdx
> +          value: ['01082210886','01082230886', '01082210886', '01082210886','01082210886','01082210886', '01082210886', '01082210886','01082210886','01082210886', '01082210886', '01082210886','010822
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 그래요

2019-10-08 11:34 UTC, ddalpange approved these changes

2020-02-10 05:58 UTC, chiabi commented
oui에서 진행하도록 하겠습니당

2020-02-10 05:58 UTC, closed without merging