feat: react-id-swiper 제거
pedaling/class101-ui pull request #133
Opened 2019-10-17 12:29 UTC by ddalpange

1. react-id-swiper를 제거하고 직접 swiper를 래핑
2. carousel을 swiper로 바꿉니다.

2019-10-17 15:11 UTC, sim-zi requested changes

2019-10-17 15:11 UTC, sim-zi commented on src/components/Carousel/ViewAllButton/index.tsx
> +      <AllButton color={ButtonColor.ORANGE_LIGHT} className={`swiper-slide ${className}`} {...props}>
```suggestion
      <AllButton color={ButtonColor.ORANGE_LIGHT} className={classnames('swiper-slide', className)} {...props}>
```

2019-10-17 15:11 UTC, sim-zi commented on src/components/Carousel/index.tsx
> +export type CarouselProps = UsingSwiperProps & OwnCarouselProps;
```suggestion
export type CarouselProps = {
  swiperProps: UsingSwiperProps;
  ...나머지 OwnCarouselProps
}
```

이렇게 하는 것이 Swiper prop을 나눠서 관리할 수 있어서 가독성이 좋고, 미래에 swiper의 prop 변경 때문에 own carousel prop과 이름이 겹치는 일이 없습니다

이 변경을 적용하면 `getSwiperParams()` 을 쉽게 제거할 수 있습니다

2019-10-17 15:11 UTC, sim-zi commented on src/components/Carousel/index.tsx
> +type UsingSwiperProps = Pick<
```suggestion
type SwiperPropsForCarousel = Pick<
```

이런 이름이 어떨까유

2019-10-17 15:11 UTC, sim-zi commented on src/components/Swiper/ArrowNavigation/index.tsx
> +  type: 'button',
button인데 type button을 또 해야하는 이유가 있을까유!

2019-10-17 15:11 UTC, sim-zi commented on src/components/Swiper/ArrowNavigation/index.tsx
> +  /* Customize navigation button  */
가독성을 위해 new line을 하나 넣어줍시다

2019-10-17 15:11 UTC, sim-zi commented on src/components/Swiper/ArrowNavigation/index.tsx
> +  margin-top: 0;
position: absolute인데 margin 설정이 필요한가요?

만약 default style을 리셋하는 거라면, 24라인에 위치하는게 좋겠습니다

2019-10-17 15:11 UTC, sim-zi commented on src/components/Swiper/DefaultNavigation/index.tsx
> +const Button = styled(IconButton)<{ direction: string }>`
```suggestion
const Button = styled(IconButton)<{ direction: keyof navigationDirectionStyle }>`
```

이렇게 해주면 direction 에 right, left 외에 값을 잘못 넣어 생기는 에러를 방지할 수 있습니다.
하지만 이렇게 타이핑을 하면, Button의 코드가 navigationDirectionStyle의 값에 종속되게 됩니다.

이 종속성을 역전시키기 위해서는 기존 코드의 `NavigationDirection` 을 다시 살리는게 좋겠습니다.

`NavigationDirection` 를 살려주세요

2019-10-17 15:11 UTC, sim-zi commented on src/components/Swiper/Slide/index.tsx
> +  return <div className={`swiper-slide ${props.className}`}>{props.children}</div>;
```suggestion
  return <div className={classnames('swiper-slide', props.className)}>{props.children}</div>;
```

2019-10-17 15:11 UTC, sim-zi commented on src/components/Swiper/index.tsx
> +  /* eslint-disable */
다 disable하지 말고, 필요한 라인에 필요한 rule만 disable 합시당.
모두 다 disable 해버리면 무엇때문에 disable 했는지 알기 어렵고, 다른 룰로 예기치 않은 문제가 발생해도 알아채기 힘듭니다

2019-10-17 15:11 UTC, sim-zi commented on src/components/Carousel/index.tsx
> +  | 'loop'
loop 작동하던가유? 핸들러가 잘 붙는지 확인해야함

2019-10-17 15:11 UTC, sim-zi commented on src/components/Swiper/index.tsx
> +export const Swiper = (props: SwiperProps) => {
```suggestion
export const Swiper: React.FC<SwiperProps> = (props: SwiperProps) => {
```

2019-10-17 15:11 UTC, sim-zi commented on src/components/Swiper/index.tsx
> +export const Swiper = (props: SwiperProps) => {
이걸 하면 107라인의 타입 캐스트가 불필요하지 않을까..? 하고 예상해봅니다

2019-10-17 15:11 UTC, sim-zi commented on src/components/Swiper/index.tsx
> +          padding-left: ${props.lgSlidesSideOffset}px;
offset은 number 타입이며, 어떤 값이든 들어올 수 있기 때문에 styled.xx`` 안에서 사용하면 유니크한 number 별로 class가 각각 생성되기 때문에 class가 지나치게 많이 생성될 우려가 있습니다.
offset이 지나치게 다양해지는 경우는 별로 없긴 하겠지만, 이런 경우에는 styled.xx`` 내부가 아니라 jsx에서 inline style로 스타일을 수정하는 것이 좋습니다

2019-10-17 15:11 UTC, sim-zi commented on src/components/Swiper/index.tsx
> +          padding-left: ${props.smSlidesSideOffset}px;
위의 코멘트와 마찬가지

2019-10-17 15:11 UTC, sim-zi commented on src/components/Swiper/index.tsx
> +      `};
```const navigationStyleByPosition: {[key in SwiperNavigationPosition]: ReturnType<typeof css> }```
이런 거 만들어서 이부분 코드를 깔끔하게 할 수 있을까용?

(`ReturnType<typeof css>`는 생각이 안 나서 저렇게 썼는데, styled-components에서 타입 import 할 수 있을 듯)

2019-10-17 15:13 UTC, sim-zi requested changes

2019-10-17 15:13 UTC, cheolee commented on src/components/Swiper/index.tsx
> +    props.transparentPagination &&
```suggestion
    props.transparentPagination ? ~~ : ''
```

template literal 문법에서 boolean 값을 쓰면 `true` `false`그대로 문자열로 변환됩니다.
그러니 빈 문자열로 해줍시다

2019-10-18 02:51 UTC, chiabi commented on src/components/Carousel/ViewAllButton/index.tsx
> +      <AllButton color={ButtonColor.ORANGE_LIGHT} className={`swiper-slide ${className}`} {...props}>
classnames 걷어내려공
https://github.com/pedaling/class101-ui/pull/124#discussion_r330489230

2019-10-18 02:59 UTC, chiabi commented on src/components/Swiper/ArrowNavigation/index.tsx
> +  type: 'button',
styled-component의 attrs는 사용하지 말자

https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md#v410---2018-11-12

2019-10-18 09:39 UTC, ddalpange commented on src/components/Carousel/index.tsx
> +  | 'loop'
핸들러는 잘 붙으나 리액트에서 렌더동작이 요상띠

2019-10-18 10:00 UTC, cheolee commented on src/components/Carousel/ViewAllButton/index.tsx
> +      <AllButton color={ButtonColor.ORANGE_LIGHT} className={`swiper-slide ${className}`} {...props}>
이 상황처럼 className을 직접 지정해줘야하는 상황이 있는데, styled components 으로 하는 건 불가능한듯 한데?!! 클래스 네임을 직접 template literal 로 표현하면 실수가 너무 많기 때문에, classnames를 걷어낼 거라면 이 상황에 대한 유틸을 만드는게 좋을 듯. 근데 굳이 걷어낼 필요가 있나..?
@chiabi @bae-unidev

2019-10-18 10:06 UTC, sim-zi requested changes

2019-10-18 10:06 UTC, cheolee commented on package.json
> +  "version": "7.0.0-test-swiper7",
정식 버전으로 바꿔주세요

2019-10-18 10:06 UTC, cheolee commented on src/components/Swiper/index.tsx
> +  /* eslint-disable */
제이든과 함 봐주이소

2019-10-18 11:24 UTC, john015 commented on src/components/Swiper/index.tsx
>    useEffect(() => {
useEffect 2개끼리 중복되는 코드가 있어서 한개만 쓰고 이렇게 쓰는게 더 깔끔할듯
```suggestion
  useEffect(() => {
    swiperRef.current = new OriginalSwiper(`#${containerId}`, swiperOptions);
    if (getSwiperInstance) {
      getSwiperInstance(swiperRef.current);
    }
    return () => {
      if (swiperRef.current) {
        swiperRef.current.destroy(true, true);
      }
    };
  }, [containerId, swiperRef, swiperOptions, getSwiperInstance]);
```

2019-10-18 12:21 UTC, john015 approved these changes

2019-10-21 06:09 UTC, bae-unidev commented on package.json
> +    "eslint-plugin-prettier": "^3.1.1",
요건 왜 추가되었나용

2019-10-21 06:09 UTC, bae-unidev commented on src/components/Carousel/index.tsx
> +import { SIZES } from '../../core/BreakPoints';
import 하는 것들 전부 internal.ts에서 가져올 수 없나?

2019-10-21 06:09 UTC, bae-unidev commented on src/components/Swiper/ArrowNavigation/index.tsx
> +  /* Reset swiper's default style */
주석 제거해주세용

2019-10-21 09:59 UTC, ddalpange commented on src/components/Swiper/index.tsx
>    useEffect(() => {
수정완료띠

2019-10-21 10:01 UTC, ddalpange commented on package.json
> +    "eslint-plugin-prettier": "^3.1.1",
개발도중 에러나서 깔았는데 PR의 책임분리를 지키지 못했엄 ....

2019-10-21 10:01 UTC, ddalpange commented on src/components/Carousel/index.tsx
> +import { SIZES } from '../../core/BreakPoints';
internal.ts라는 모아주는 파일을 폴더마다 둔다는거야?

2019-10-21 10:07 UTC, ddalpange commented on package.json
> +    "eslint-plugin-prettier": "^3.1.1",
분리완료띠

2019-10-21 10:08 UTC, ddalpange commented on src/components/Swiper/ArrowNavigation/index.tsx
> +  /* Reset swiper's default style */
넹

2019-10-21 10:16 UTC, bae-unidev commented on src/components/Carousel/index.tsx
> +import { SIZES } from '../../core/BreakPoints';
internal module 패턴을 찾아봐 mobx 레포를 봐두 좋구
순환참조 문제를 해결해야해서 이렇게 접근하면 의존성이 꼬여 ㅠㅜ

2019-10-21 13:54 UTC, bae-unidev approved these changes

2019-10-21 13:54 UTC, bae-unidev commented on src/components/Swiper/Slide/index.tsx
> +import classNames from 'classnames';
.swiper-slide를 styled component로 쓸 수 없는 경우지? 
이 의존성은 쉽게 우리 코드 베이스를 어지럽힐 수 있을것 같애(누군가가 styled-component를 안쓰고 className으로 스타일링을 한다거나?). 뭔가 방지하는 방법이 있어야 할것 같은데, 고민해줘~

2019-10-22 05:15 UTC, sim-zi requested changes

2019-10-22 05:15 UTC, cheolee commented on src/components/Swiper/DefaultNavigation/index.tsx
> +      left: auto;
left 는 항상 들어가서, 분기처리 안해도 될듯?

2019-10-22 05:15 UTC, cheolee commented on src/components/Swiper/index.tsx
> +  className: '',
undefined로 내비두면 안되남?!

2019-10-22 05:15 UTC, cheolee commented on src/components/Swiper/index.tsx
> +  freeMode: true,
freeMode가 default인게 좋은 걸까.. 흑 mobile UX를 생각하면 free가 아닌게 좋을듯한데...
(그냥 투정임..)

2019-10-22 05:15 UTC, cheolee commented on src/components/Swiper/index.tsx
> +  slideToClickedSlide: false,
기본값이 false라서 지정 안해줘도 될듯

2019-10-22 05:15 UTC, cheolee commented on src/components/Swiper/index.tsx
> +export interface SwiperProps extends SwiperOptions {
swiper의 모든 옵션을 열어두지 말고, 우리 디자인 시스템에서 허용하는 것만 바꾸게 해야할듯 한데
우리 디자인 시스템의 용어로 바꿔서 prop을 열어줘야할듯.

@chiabi 랑 디자이너들이랑 얘기 함 해보아야할듯합니다
이 pr에는 반영 안 돼도, 한 번 봐야할듯. 이거 한 번 열면 나중에 수습 어려워서

2019-10-22 05:32 UTC, ddalpange commented on src/components/Swiper/index.tsx
> +export interface SwiperProps extends SwiperOptions {
@cheolee 그 개념이 Carousel이긴 한데 ....
Swiper는 export를 안해주는게 맞으려나? ㅋㅋ

2019-10-22 05:49 UTC, cheolee commented on src/components/Swiper/index.tsx
> +export interface SwiperProps extends SwiperOptions {
아 맞네 잘못봤습니다 ㅈㅅ

2019-10-22 05:50 UTC, cheolee commented on src/components/Swiper/index.tsx
> +export interface SwiperProps extends SwiperOptions {
그렇담 스와이퍼 옵션을 extend 하는 것보다는, 별도의 object로 prop에 넘겨주게 하는게 좋겠슴다

2019-10-22 05:50 UTC, cheolee commented on src/components/Swiper/index.tsx
> +export interface SwiperProps extends SwiperOptions {
우리가 구현한 스와이퍼 컴포넌트와 prop 이름의 충돌 우려가 있어서

2019-10-22 05:51 UTC, chiabi commented
SlideSideOffset 기존이랑 약간 동작이 다르다

<img width="413" alt="Screen Shot 2019-10-22 at 2 50 21 PM" src="https://user-images.githubusercontent.com/15900134/67261386-66218a00-f4db-11e9-8ea8-0ef4ae46b6dd.png">

현재 PR
<img width="413" alt="Screen Shot 2019-10-22 at 2 51 00 PM" src="https://user-images.githubusercontent.com/15900134/67261387-66218a00-f4db-11e9-8049-d560a8389bc7.png">

2019-10-22 05:52 UTC, cheolee commented on src/components/Swiper/index.tsx
> +  slideToClickedSlide: false,
다른 것도 기본값인건 지워줍시다유

2019-10-22 07:14 UTC, ddalpange commented on src/components/Swiper/index.tsx
> +export interface SwiperProps extends SwiperOptions {
음 carousel에서 이미 그렇게 하고 있는데 swiper도 그렇게 구분을 지어야할까?
swiper component와 swiper까지 구분짓는건 낭비인거가테 ㅇㅅㅇ
나중에 삭제해야할 때 저는 swiper component 자체를 삭제해야한다고 생각합니다!
@cheolee

2019-10-22 07:46 UTC, merged