feat: Avatar 컴포넌트 추가
pedaling/class101-ui pull request #136
Opened 2019-10-22 08:17 UTC by tbvjaos510

Comment 컴포넌트를 만들기 전에 필요한 Avatar컴포넌트를 완성하였습니다

![image](https://user-images.githubusercontent.com/32216112/67268588-c7535880-f4ef-11e9-8fc6-a95abcf0efb3.png)
![image](https://user-images.githubusercontent.com/32216112/67268596-d0442a00-f4ef-11e9-8d55-cac5e40d8cc1.png)

2019-10-22 08:25 UTC, chiabi commented on src/components/Avatar/index.tsx
> +export interface AvatarProps extends React.ImgHTMLAttributes<HTMLImageElement> {
지정한 props를 제외하고 HTML attributes는 [HTMLElement]Attributes 같은 props로 받는게 좋을 것 같습니다.

히스토리: https://github.com/pedaling/class101-ui/pull/25#discussion_r262352472

2019-10-22 08:30 UTC, tbvjaos510 commented on src/components/Avatar/index.tsx
> +export interface AvatarProps extends React.ImgHTMLAttributes<HTMLImageElement> {
수정하겠습니다!

2019-10-22 08:33 UTC, chiabi commented
그리고 서비스의 프로필은 서비스의 Image컴포넌트를 사용해서 ImageUtils에서 옵션 사이즈로 src를 조합하는데 그 부분은 이 컴포넌트랑 어떻게 사용할 수 있을지 효용이 있을지 @ddalpange 이랑 얘기해봤으면 좋겠음!

2019-10-22 08:35 UTC, tbvjaos510 commented on docs/components/Avatar.ts
> +export const IMAGE_URL_2 = 'https://cdn.class101.net/images/d0b1b421-6cce-48cc-bd98-2c4b95323552/640xauto';
실제 사용자 프로필을 사용해도 문제가 없을까?? 일단 사용은했는데 문제있으면 다른 사진으로 대체해야할 것 같아서

2019-10-22 08:37 UTC, chiabi commented on docs/components/Avatar.ts
> +export const IMAGE_URL_2 = 'https://cdn.class101.net/images/d0b1b421-6cce-48cc-bd98-2c4b95323552/640xauto';
호오 사용자는 안될 듯! 다른 걸로 대체하자

2019-10-22 09:04 UTC, bae-unidev requested changes

2019-10-22 09:04 UTC, bae-unidev commented on src/components/Avatar/index.tsx
> +          <AvatarImage src={src} {...imageAttributes} />
src를 못 가져오는 경우도 대비하자. onError로 못가져 온 경우 텍스트 표시하게 바꿔줘~

2019-10-22 09:04 UTC, bae-unidev commented on docs/components/Avatar.mdx
> +    icon={
iconPosition을 정할 수 있게 하자! Position.ts를 보면 위치 정보를 미리 enum으로 만들어 둔게 있는데 그걸로 설정 가능하게 만들자!

2019-10-23 08:29 UTC, tbvjaos510 commented
요찡이와 이야기해 본 결과 `imageAttributes`는 혼란을 가져와서 그냥 사용할 수 있는 props를 제한하였습니다
* iconPosition props 추가
* imageAttributes 삭제
* srcSet, alt 추가
* `onClick`, `onIconClick`, `onError` 추가
* 이미지를 불러오지 못할 시 텍스트가 표시되게 변경

2019-10-23 08:30 UTC, bae-unidev approved these changes

2019-10-24 02:39 UTC, merged