feat: comment 컴포넌트 추가
pedaling/class101-ui pull request #146
Opened 2019-11-04 11:20 UTC by tbvjaos510

Comment 컴포넌트를 추가하였습니다.

![image](https://user-images.githubusercontent.com/32216112/68117070-bb2fb800-ff3f-11e9-8cfb-c9506d660644.png)

2019-11-04 14:33 UTC, hjinu commented
와 이거 개깔끔하다

2019-11-05 00:33 UTC, tbvjaos510 commented on src/components/Comment/Content/index.tsx
> +      -webkit-line-clamp: ${props.maxLine};
댓글 줄이기는 `-webkit-line-clamp`를 사용했는데, chrome, safari, firefox, ios safari, android chrome에서 테스트해보았습니다. 다른 브라우저 테스트가 필요하면 말해주세요!

2019-11-05 02:17 UTC, ddalpange requested changes

2019-11-05 02:17 UTC, ddalpange commented on src/components/Comment/Action/index.tsx
> +const Container = styled.div<{ position: ButtonIconPosition; visible: boolean }>`
이 타입은 인라인으로 쓰지 말구
Props에서 Pick해서 쓰자

2019-11-05 02:17 UTC, ddalpange commented on src/components/Comment/Action/index.tsx
> +  visible: boolean;
이것은 css의 `visibility: none;`이 생각나는데 하는 일은 `display: false;`입니다.
좀 더 정확한 변수명으로 변경 부탁드립니다 ㅇㅅㅇ.

2019-11-05 02:17 UTC, ddalpange commented on src/components/Comment/Action/index.tsx
> +  extends Omit<IconButtonProps, 'leftIcon' | 'rightIcon' | 'color' | 'size' | 'theme'> {
이거 나중에 쓸 수도 있으니 타입을 한번 더 빼주자
type ButtonPropsForComment

2019-11-05 02:17 UTC, ddalpange commented on src/components/Comment/Action/index.tsx
> +  align-items: center;
고정 css는 위에 해주고 조건부 css를 아래로 정렬해주라!

2019-11-05 02:17 UTC, ddalpange commented on src/components/Comment/Content/index.tsx
> +  private handleClampToggleButtonClick = () => {
```suggestion
  private handleToggleClampButton = () => {
```

2019-11-05 02:17 UTC, ddalpange commented on docs/components/Comment.mdx
> +- onClick, disabled와 같은 props는 [IconButton Props](/components/icon-button#props)를 상속받습니다.
요런것은 docz보단 jsdoc으로 달아줍시다.
IDE가 파싱해서 보여주기도 함.

2019-11-05 03:29 UTC, tbvjaos510 commented on src/components/Comment/Action/index.tsx
> +  visible: boolean;
active로 수정해볼게!

2019-11-05 04:14 UTC, tbvjaos510 commented on src/components/Comment/Action/index.tsx
> +  visible: boolean;
display로 수정했습니당

2019-11-05 05:10 UTC, ddalpange approved these changes
수고많으셨어용

2019-11-05 05:14 UTC, bae-unidev approved these changes
굿!! 최고야! 이제 웹 리펙터링하자 ㅎㅎ

2019-11-05 05:14 UTC, bae-unidev commented on docs/components/Comment.mdx
> +    time="2시간 전"
요거 timeText로 하거나, time에 Date도 넣을 수 있게 바꾸는게 좋을듯?

2019-11-05 05:14 UTC, bae-unidev commented on docs/components/Comment.mdx
> +      <div>
<>

2019-11-05 08:28 UTC, merged