feat: section linkText style 변경
pedaling/class101-ui pull request #154
Opened 2019-11-11 03:04 UTC by john015

2019-11-11 03:09 UTC, chiabi requested changes

2019-11-11 03:09 UTC, chiabi commented on src/layout/Section/Header.tsx
> +import { Colors } from '../../core';
```suggestion
import { gray600 } from '../../core/Colors';
```

2019-11-11 03:09 UTC, chiabi commented on src/layout/Section/Header.tsx
> +  color: ${Colors.gray600};
TextButton과는 색깔을 다르게 가자고 얘기가 나와서 수정한 거지?

2019-11-11 03:12 UTC, john015 commented on src/layout/Section/Header.tsx
> +  color: ${Colors.gray600};
ㅇㅇ 맞아

2019-11-11 03:13 UTC, john015 commented on src/layout/Section/Header.tsx
> +import { Colors } from '../../core';
Colors로 import하는게 우리 컨벤션 아니야? 
Class101 레포에서는 다 이렇게 쓰던데

2019-11-11 05:55 UTC, chiabi commented on src/layout/Section/Header.tsx
> +import { Colors } from '../../core';
ui 안에서 이렇게 하면 Colors가 트리쉐이킹이 안될텐데 
class101이 아니라 ui 내의 다른 컴포넌트 참고해주라 ui 내에서는 컬러 빼서 쓰고 있음

2019-11-11 07:07 UTC, john015 commented on src/layout/Section/Header.tsx
> +import { Colors } from '../../core';
트리쉐이킹 이슈가 있었네 기존에 Colors로 되어 있던 것도 다 바꿨어.

2019-11-12 03:53 UTC, chiabi commented on src/components/Comment/index.tsx
> +              <Caption1 fontWeight="600" color={gray800}>
우리 기본 컬러 gray800이라서 없어도 될거인디

2019-11-12 03:58 UTC, chiabi commented on src/components/Comment/Content/index.tsx
> +  color: ${gray800};
font-size: 14px부터 body2로 쓸 수 있는 스타일입니당.
color는 기본 컬러가 gray800이라서 필요가 없습니다. 
```suggestion
  ${body2};
  margin-top: 6px
```

2019-11-12 03:59 UTC, john015 commented on src/components/Comment/Content/index.tsx
> +  color: ${gray800};
흠 기존에 왜 이렇게 되어있던거지

2019-11-12 04:01 UTC, john015 commented on src/components/Comment/Content/index.tsx
> +  color: ${gray800};
@tbvjaos510 참고해주세여

2019-11-12 04:02 UTC, tbvjaos510 commented on src/components/Comment/Content/index.tsx
> +  color: ${gray800};
넵!!!

2019-11-12 04:17 UTC, chiabi approved these changes

2019-11-12 04:17 UTC, merged