[WIP] feat: Navigation에 shouldOpenWindow로 새 창 열기를 할 수 있다
pedaling/class101-ui pull request #162
Opened 2019-11-15 13:13 UTC by chiabi

- core에 LinkBlock이 추가되고 https:// http://로 시작할 경우 native
anchor를 사용한다

2019-11-15 13:13 UTC, chiabi commented
이거 괜찮으면 Card, Section등 링크 사용하는 컴포넌트를 교체할 예정입니다.

2019-11-15 14:41 UTC, ddalpange commented
이거 하는 김에 gatsby와 next의 링크도 지원하게 하자! 내가 도와줄겡 @chiabi

2019-11-17 13:20 UTC, hrg921 commented on docs/components/Button.mdx
> +> - v7부터 기존의 color, backgroundColor는 지원하지 않습니다.
우리도 Release Notes같은게 있다면 좋겠군

2019-11-17 13:21 UTC, hrg921 commented on docs/components/Button.mdx
> +> - v7부터 기존의 color, backgroundColor는 지원하지 않습니다.
https://github.com/pedaling/class101-ui/releases/tag/v7.0.0 뭐야뭐야 언제쓰기 시작한거야 ㅋㅋㅋ

2019-11-18 07:58 UTC, chiabi commented on docs/components/Button.mdx
> +> - v7부터 기존의 color, backgroundColor는 지원하지 않습니다.
아마도 v6부터 썼음ㅋㅋㅋㅋ

2019-11-19 03:33 UTC, ddalpange requested changes
우리 이거 target을 안받고 shouldOpenWindow로 해야하는 이유가 있어?

2019-11-19 03:49 UTC, chiabi commented
target="_blank"를 넣지만 실제로는
{ target: '_blank', rel: 'noopener noreferrer' }로 설정해줄 거라서 다른 네이밍의 props로 사용하는 거
기존 button은  target을 받도록 했는데 그러면 위의 문제가 있을 것 같아서!
근데 external이라는 boolean 프로퍼티가 네이밍으로 더 적합할 것 같기도 하다

2019-11-19 04:13 UTC, ddalpange approved these changes

2019-11-19 04:18 UTC, merged