feat(ui, mdx): Pagination에 많은 데이터가 들어와도 적당히 대응 가능하게 수정
pedaling/class101-ui pull request #189
Opened 2020-02-05 06:59 UTC by lonyele

Figma: [Pagination component](https://www.figma.com/file/BPv3p1SEYUKhuKyYW3syfTgq/Product_System_Component?node-id=4657%3A7899)

## What I did
pagination numbered 버튼들을 최대 5개까지 보여주고 맨앞/뒤쪽이 아닌이상 현재 선택된 currentPageIndex가 중앙에 보이도록 수정

## Context
쿤과 이야기를 해서 현재 가장 심플한 정도의 대응만 가능하게 수정 했습니다. 나중에 반응형또는 이걸 구현하는대에도 방법이 많이 있는데 추후에 논의 하면 될 것 같습니다.

##### 이전 &#8628;
<img width="959" alt="스크린샷 2020-02-05 오후 3 42 19" src="https://user-images.githubusercontent.com/15892571/73818088-e58b5d00-482f-11ea-8bef-0f6d9b476c7b.png">

##### 변경후 &#8628;
![화면 기록 2020-02-05 오후 3 41 26-1](https://user-images.githubusercontent.com/15892571/73818297-634f6880-4830-11ea-8f48-6fd5aa061f49.gif)

2020-02-05 07:02 UTC, ddalpange requested changes

2020-02-05 07:02 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +    if (totalPageIndex < 5) {
5를 의미를 가진 상수로 선언하면 해당 주석은 필요가 없어질 듯.

2020-02-05 07:02 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +    if (currentPageIndex - 2 <= 0) {
위와 동일합니다.

2020-02-05 07:02 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +    // 맨 뒤에서부터 5개 보여주기
위외 동일합니다.

2020-02-05 07:02 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +    if (currentPageIndex + 2 >= totalPageIndex) {
위와 동일합니다.

2020-02-05 07:02 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +    return range(currentPageIndex - 2, currentPageIndex + 3);
위와 동일합니다.

2020-02-05 07:02 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +    const indexList = this.getIndexList(currentPageIndex, totalPageIndex);
```suggestion
    const indexListToDisplay = this.getIndexList(currentPageIndex, totalPageIndex);
```

2020-02-05 11:39 UTC, lonyele commented on src/components/Pagination/index.tsx
> +    if (totalPageIndex < 5) {
다음에 추가할 기능이었는데 그냥 지금 했음요

2020-02-05 11:39 UTC, lonyele commented on src/components/Pagination/index.tsx
> +    if (currentPageIndex + 2 >= totalPageIndex) {
완료!

2020-02-05 11:39 UTC, lonyele commented on src/components/Pagination/index.tsx
> +    if (currentPageIndex - 2 <= 0) {
완료!

2020-02-05 11:39 UTC, lonyele commented on src/components/Pagination/index.tsx
> +    return range(currentPageIndex - 2, currentPageIndex + 3);
완료!

2020-02-05 11:39 UTC, lonyele commented on src/components/Pagination/index.tsx
> +    const indexList = this.getIndexList(currentPageIndex, totalPageIndex);
완료!

2020-02-05 11:44 UTC, lonyele commented
흠... 이건 그냥 나중에 할려던건데 이왕 하는김에 했슴다. prop으로 보여주고 싶은 numbered pagination 버튼 개수를 내려줄수 있게 바꿨습니다. 이건 추후에 이 컴포넌트가 어느 넓이에서 쓰이든 사용할수 있게 만든거고 mutation observer같은거 써서 하면은 반응형 하게도 만들수 있겠네요
![화면 기록 2020-02-05 오후 8 42 09](https://user-images.githubusercontent.com/15892571/73838955-3616b080-4858-11ea-9c47-a0738950a5ad.gif)

2020-02-06 06:07 UTC, ddalpange requested changes
주석은 해당 경우에 쓰면 좋을 것 같아요.
1. 특별한 도메인 특성을 가지고 있다.
2. 주의해야하는 이전 히스토리
3. 정말 리얼루다가 복잡띠
페이지네이션 컴포넌트는 위 3가지 중 해당되는게 없어 보입니다.
주석 없이 코드를 이쁘게 이쁘게 써봅시당.

2020-02-06 06:07 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +  showingNumberedIndexButtonCount?: number;
```suggestion
  pageCountPerView?: number;
```

2020-02-06 06:07 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +      return 5;
```suggestion
      return DEFAULT_PAGE_COUNT_PER_VIEW;
```

2020-02-06 06:07 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +  // currentPageIndex가 중앙에 보여지는 상황 때문에 홀수만 받습니다.
필요 없는 주석.

2020-02-06 06:07 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +    const aroundCurrentNumberedIndexShowingCount = Math.floor(showingNumberedIndexButtonCount / 2);
```suggestion
    const sidePageCountToView = Math.floor(showingNumberedIndexButtonCount / 2);
```

이 정도로 해도 되지 않을까용? 주석은 필요 없어 보임.

2020-02-06 06:07 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +      return range(0, totalPageIndex + 1);
헷갈리는게 조금 있는게 내가 만약 5개를 보여주고 싶다면 totalPageIndex는 3인거야? 0부터 4까지 인 것 같은뎅.

2020-02-06 06:07 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +  showingNumberedIndexButtonCount?: number;
또는 pageLimitToDisplay 정도로 하면 쉬울 듯.

2020-02-06 06:07 UTC, ddalpange commented on src/components/Pagination/index.tsx
> +    if (currentPageIndex - aroundCurrentNumberedIndexShowingCount <= 0) {
```suggestion
    if (currentPageIndex  <=  aroundCurrentNumberedIndexShowingCount) {
```
이렇게 하는게 이해하기 더 쉬울 듯.

2020-02-06 07:54 UTC, lonyele commented on src/components/Pagination/index.tsx
> +      return range(0, totalPageIndex + 1);
요찡 말한대로 할려면  `showingNumberedIndexButtonCount={5}` 가 되는거고 `totalPageIndex` 요거는 데이터가 많으면 작고 많으면 큰 숫자가 들어오게 되는데 
##### 일반적인 케이스가 1번이고
ex1) 총 보여줄 데이터가 100개 -> 버튼 하나에 10개씩 보여준다면 총 10개의 버튼이 생겨야 하는데(`totalPageIndex는 9`) 5개를 보여주고 싶으면(`showingNumberedIndexButtonCount는 5`) 5개씩 보여주면됨
##### 요 if문이 있는 케이스가 2번인데
ex2) 총 보여줄 데이터가 6개 -> 버튼 하나에 5개씩 보여준다면 총 2개의 버튼이 생겨야 하는데(`totalPageIndex는 1` ) 5개를 보여주게 설정했더라도(`showingNumberedIndexButtonCount는 5`) 보여줄수 있는 데이터 자체가 적어서 총 버튼은 2개만 보여주게 하는 예외처리? 로직 

`lodash`의 [`range`함수의 2번째 인자값의 숫자는 포함하지 않고 만들어서 그럼](https://lodash.com/docs/#range)  

> Creates an array of numbers (positive and/or negative) progressing from start up to, but not including, end. 

그래서 다시 2번째 예시의 마지막 부분 더 설명하면  `range(0, totalPageIndex + 1);` 이부분이 -> `range(0, 1 + 1);` -> `range(0, 2);` -> `[0, 1]` 이렇게 되어서 총 2개의 버튼을 보여주게 됨

2020-02-06 08:10 UTC, lonyele commented on src/components/Pagination/index.tsx
> +    if (currentPageIndex - aroundCurrentNumberedIndexShowingCount <= 0) {
완료!

2020-02-06 08:11 UTC, lonyele commented on src/components/Pagination/index.tsx
> +    const aroundCurrentNumberedIndexShowingCount = Math.floor(showingNumberedIndexButtonCount / 2);
완료!

2020-02-06 08:11 UTC, lonyele commented on src/components/Pagination/index.tsx
> +  // currentPageIndex가 중앙에 보여지는 상황 때문에 홀수만 받습니다.
완료!

2020-02-06 08:11 UTC, lonyele commented on src/components/Pagination/index.tsx
> +      return 5;
완료!

2020-02-06 08:11 UTC, lonyele commented on src/components/Pagination/index.tsx
> +  showingNumberedIndexButtonCount?: number;
완료!

2020-02-06 11:29 UTC, ddalpange approved these changes

2020-02-06 19:15 UTC, merged