refactor: ProgressBar 컴포넌트를 리팩토링한다
pedaling/class101-ui pull request #216
Opened 2020-03-24 12:42 UTC by chiabi

- 사용하지 않는 스냅샷 제거
- 리플로우 일으키는 스타일링 리팩토링
- 애니메이션 문서 추가

2020-03-24 14:50 UTC, sim-zi requested changes

2020-03-24 14:50 UTC, cheolee commented on src/components/ProgressBar/index.tsx
> +    const barValue = Number(value);
이미 number여서 Number로 감쌀 필오ㅛ 없을 듯! barValue 대신 value로 씁시당!
```suggestion
```

2020-03-24 14:50 UTC, cheolee commented on src/components/ProgressBar/index.tsx
> +    }
```suggestion
    const percent = Math.max(0, Math.min(100, barValue));
```

이 값은 특정 css와 엮여있다기보단 percent 값을 뜻하니, 요런 이름이 어떨까요?

(+ 민맥스를 이용한 number range 처리)

2020-03-25 03:07 UTC, john015 approved these changes

2020-03-25 03:13 UTC, merged