refactor: skeleton의 layout관련 props들은  inlineStyle로 적용한다
pedaling/class101-ui pull request #218
Opened 2020-03-25 08:37 UTC by chiabi

2020-03-25 13:55 UTC, sim-zi requested changes

2020-03-25 13:55 UTC, cheolee commented on src/components/Skeleton/Skeleton.tsx
> +      }
rounded와 circle은, 각각 두 가지 케이스밖에 없어서 styled-component로 class를 생성되게 해줘도 좋을 거 같아!

width, height의 경우는 바리에이션이 많으니 inline style을 쓰고! (근데 이것도 사실 논란의 여지가 있긴 함. lnline style 사용으로 인한 브라우저 렌더링 상의 오버헤드 vs css in js 사용으로 인한 스크립팅 오버헤드)

2020-03-26 02:15 UTC, chiabi commented on src/components/Skeleton/Skeleton.tsx
> +      }
흑흑 양날의 검쓰....ㅠㅠ

2020-03-26 05:00 UTC, sim-zi approved these changes
굿입니당

LGTM!

2020-03-26 05:00 UTC, cheolee commented on src/components/Skeleton/Skeleton.tsx
> +    }, [width, height, style]);
(그냥 참고차 공유하는 코드)

만약 width, height, style이 자주 바뀌고, 스타일 계산하는게 복잡하다면 더 최적화하기 위해 아래처럼 바꿀 수도 이씀
근데 지금은 바뀌는 일이 드물고, 로직이 짧다보니 현재 코드가 나을 듯

```
const skeletonInlineStyle = useMemo(() => {
  // width, height가 바뀔 때만 새로 계산됨
  ...
  return inlineStyle;
}, [width, height]);

const mergedStyle = useMemo(() => {
  return { style, ...skeletonInlineStyle };
}, [style, skeletonInlineStyle]);
```

2020-03-26 07:29 UTC, merged