feat(ui): Overlay 컴포넌트를 추가한다.
pedaling/class101-ui pull request #220
Opened 2020-04-02 03:31 UTC by moodselah

Overlay 컴포넌트를 추가했습니당

2020-04-02 03:42 UTC, sim-zi reviewed
1. 다른 곳에서 사용되는 Overlay와 거의 동일한 코드이니, 하나의 Overlay 코드만 두고, 다른 컴포넌트에서 가져가서 사용하도록 리팩토링 하면 좋을 듯..!!

2. 더 리팩토링 한다면 Portal과 Overlay가 포함된, `<OverlaidPortal>`을 만들면 좋을 듯... 모달과 같이 화면 전체를 덮어 나타나는 녀석들을 위한...
prop은
```
type Props = {
  opened: boolean; // 네이밍 컨벤션 얘기가 나오고 있는 부분인데, 일단 기존 prop 작명법을 따름...
  dimmer: boolean; // 까만색 overlay 존재 여부
  ...
}
```


근데, 비슷한 것을 oui에서 만들고 있어서 1번의 리팩토링만 해도 괜찮을 듯 합니다 (overlay 스타일 정도라두 리팩토링 하면 좋을 듯!)

2020-04-02 04:09 UTC, chiabi commented on src/overlays/Overlay/index.tsx
> +    document.body.style.overflow = 'hidden';
utils/ssr 에 isClient라는 함수가 있는데 그걸로 체크해주는게 좋을 것 같습니다
```suggestion
if (isClient()) {
    document.body.style.overflow = 'hidden';
```

2020-04-02 08:18 UTC, sim-zi requested changes
잠시 리뷰하다 일이 생겨서 나중에 이어서 리뷰합니닷

2020-04-02 08:18 UTC, cheolee commented on src/overlays/OverlaidPortal/index.tsx
> +export const OverlaidPortal = React.memo<OverlayProps>(originalProps => {
```
export const OverlaidPortal = React.memo<OverlayProps>({ className, children, dimmer = true, overlayColor, opened, closable = true, ... }) => {
```

함수형 컴포넌트에서 defaultProps 설정 이렇게 가능!

2020-04-02 08:19 UTC, moodselah commented on src/overlays/OverlaidPortal/index.tsx
> +export const OverlaidPortal = React.memo<OverlayProps>(originalProps => {
대박쓰.... 감사루!!!

2020-04-02 08:22 UTC, moodselah commented on src/overlays/OverlaidPortal/index.tsx
> +export const OverlaidPortal = React.memo<OverlayProps>(originalProps => {
대박쓰.... 감사루!!!

2020-04-05 07:21 UTC, sim-zi approved these changes
작업 감사합니다!

마이너한 코멘트가 하나 있는데, 츄러스가 판단하고 반영할지 결정해주세욥!

2020-04-05 07:21 UTC, cheolee commented on src/overlays/OverlaidPortal/index.tsx
> +        onClick={closeable ? handleCloseModal : undefined}
```suggestion
        onClick={closeable ? onClose : undefined}
```

useCallback 안 쓰고 일케 해도 괜찮을 거 같다!

2020-04-06 01:54 UTC, moodselah commented on src/overlays/OverlaidPortal/index.tsx
> +        onClick={closeable ? handleCloseModal : undefined}
조와~!

2020-04-06 02:08 UTC, merged