fix: GridList에 item의 필드를 임의로 key로 지정할 수 있도록 keyName을 추가한다
pedaling/class101-ui pull request #235
Opened 2020-04-20 12:31 UTC by chiabi

- keyName이 없으면 원래대로 generate된 ID를 사용한다

InfiniteScroll이랑 같이 쓰면 깜빡임 있더라구요....

2020-04-20 13:01 UTC, iseongho commented on src/layout/GridList/index.tsx
> +            <GridListItem key={keyName ? item[keyName] : generateID()} smColumn={smColumn} lgColumn={lgColumn}>
generateID() 딴 곳에서 먼저 불러오자 저렇게 되면 렌더될 때 마다 새로운 id 만들 듯

2020-04-20 15:09 UTC, sim-zi requested changes

2020-04-20 15:09 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  keyName: string;
```
keyExtractor: (item: T) => string
```

이렇게 구현하는 쪽이 안전하고 확장성이 좋을 듯!

2020-04-20 15:15 UTC, chiabi commented on src/layout/GridList/index.tsx
> +  keyName: string;
오 좋음
이거 어차피 브레이킹 체인지인데
GridListTile 이런걸로 아이템 컨테이너를 밖으로 빼고 렌더는 알아서 처리하게 할까도 생각했음ㅠㅠ

2020-04-20 15:22 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  keyName: string;
헷헷헷헷
리액트네이티브의 flatlist 같은 거 api 참고하면 도움될듯!!

2020-04-20 15:22 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  keyName: string;
죠타죠타

2020-04-21 04:25 UTC, chiabi commented on src/layout/GridList/index.tsx
> +  keyName: string;
호오오 리액트 네이티브

2020-04-21 04:47 UTC, sim-zi requested changes

2020-04-21 04:47 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  -webkit-padding-start: 0;
이건 무엇땜에 필요햄?!

2020-04-21 04:47 UTC, cheolee commented on src/utils/index.ts
> +export * from './keyExtractor';
👍

2020-04-21 04:47 UTC, cheolee commented on src/utils/keyExtractor.ts
> +}
```suggestion
export function defaultKeyExtractor(item: Item, index: number) {
  return index;
}
```

이 함수가 크게 두 가지 역할을 하고 있는데,

1. extractor가 존재하는지 여부를 판단하고 존재하면 extractor를 사용해서 key를 반환
2. 존재하지 않으면 커스텀 extractor를 구현하여 key를 리턴

이 두 가지는 별도의 함수로 각각 존재하는 것이 좋겠음

근데 2번처럼 커스텀 extractor를 구현하면 사용하는 측에서 key로 index를 그냥 쓰고 싶었는데 item에 id나 key가 존재해서 예상대로 동작하지 않는 경우도 생길 수 있기 때문에, 기본 동작으로는 index를 리턴하게 하는 쪽이 좋을 거 같음..! (더 strict하게 간다면 아예 key를 넣지 않아서 개발자에게 key가 없다는 걸 알려주거나, GridList에서 keyExtractor를 필수로 할 수도 있고...)

그래서 결국 `return index;`하는 구문만 남았다고 한다

```
({
className, 
divAttributes,
items,
keyExtractor = defaultKeyExtractor
...
})
...
  <GridListItem key={keyExtractor(item, index)} 
...
```
이런 식으로 하면 될듯



---

- key를 string으로 변환하지 않아도 될듯
react 코드 내에서 key를 항상 string으로 변환하더라구! 그래서 우리 코드에선 깔끔하게 number 그대로 넘겨도 될듯

<img width="419" alt="image" src="https://user-images.githubusercontent.com/5275823/79825981-76a4b580-83d5-11ea-9024-666a28ea2998.png">
https://github.com/facebook/react/blob/0960b7ba580b620202f7d245bb696aca71c63e37/packages/react/src/ReactElement.js#L291

2020-04-21 04:47 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  <T extends { [key in string]: any }>({
```suggestion
  <T>({
```

items에 object[]가 아니라 number[]나 string[] 같은 것도 올 수 있으니...!

2020-04-21 04:47 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  <T extends { [key in string]: any }>({
기존에 사용하던 GridList 코드를 일일이 바꾸지 않게ㅐ 하고 싶다면 `<T = any>` 를 넣어주면 좋을 듯

2020-04-21 04:58 UTC, chiabi commented on src/layout/GridList/index.tsx
> +  -webkit-padding-start: 0;
reset이나 normalize를 넣어놓지 않아서
ul에 user agent stylesheet가 먹음... 그거 리셋하는 스타일...
`padding-inline-start: 40px;`

2020-04-21 07:00 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  -webkit-padding-start: 0;
아하! 
이거, padding: 0 으로 하는 쪽은 어떨까?!
padding-inline-start 는 비교적 최근에 나온 문법이라, padding으로 써줘버리는게 좋을 듯

2020-04-21 08:19 UTC, sim-zi requested changes

2020-04-21 08:19 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  <T extends any>({
앗 이거 내가 정확히 리뷰를 전달하지 못했다

1. items에 어떤 형태의 배열이든 들어올 수 있게
```suggestion
  <T>({
```
이렇게 해주고,

2. 만약 breaking change를 줄이고 싶다면 (T가 생기면서 기존에 사용하던 모든 GridList에 T를 설정해줘야하니)
```suggestion
  <T = any>({
```

이렇게 기본값을 지정하자는 얘기여쓰!

2020-04-21 08:19 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  <T extends any>({
근데 어쩌면 기본값을 지정하지 않아도, items를 통해서 T의 타입이 알아서 추론 될 수 있을 듯?

2020-04-21 08:19 UTC, cheolee commented on src/utils/defaultKeyExtractor.ts
> +export function defaultKeyExtractor(item: Item, index: number) {
```suggestion
export function defaultKeyExtractor(item: unknown, index: number) {
```

이렇게 어떠심

unknown은 아직 타입은 알 수 없지만, item을 사용할 때는 타입을 지정하게 강제할 수 있음
unknown을 쓰면 지금처럼 item을 쓰지 않는 상황에선 any처럼 사용되지만, 만약에 item을 사용하는 코드가 생기면 타이핑을 해줘야 하도록 강제 할 수 있음

2020-04-21 12:07 UTC, chiabi commented on src/layout/GridList/index.tsx
> +  -webkit-padding-start: 0;
위에 padding: 0 있는데 리셋이 안됨....

2020-04-21 12:12 UTC, chiabi commented on src/layout/GridList/index.tsx
> +  -webkit-padding-start: 0;
아니네 되는데 web에서 저걸 왜 넣어지 으으ㅡㅇㅁ...

2020-04-21 12:12 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  -webkit-padding-start: 0;
후후...

2020-04-21 12:35 UTC, chiabi commented on src/layout/GridList/index.tsx
> +  renderItem: any;
any

2020-04-21 12:35 UTC, chiabi commented on src/layout/GridList/index.tsx
> +  overflow: hidden;
Container 없애기

2020-04-21 12:35 UTC, chiabi commented on src/utils/defaultKeyExtractor.ts
> +export function defaultKeyExtractor(item: unknown, index: number) {
```suggestion
export function defaultKeyExtractor(_item: unknown, index: number) {
```

2020-04-21 12:49 UTC, chiabi commented on src/utils/defaultKeyExtractor.ts
> +export function defaultKeyExtractor(item: unknown, index: number) {
`_item`은 
`variable-name  variable name must be in lowerCamelCase, PascalCase or UPPER_CASE`
여기에 걸려부려서 `_`으로 넣었음

2020-04-21 12:57 UTC, sim-zi reviewed
코멘트 두 개 달아봅니다.... 헿

2020-04-21 12:57 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  renderItem: (item: T, index: number, arr: T[]) => ReactElement;
근데, arr을 쓸 일이 있나..?!!

2020-04-21 12:57 UTC, cheolee commented on src/layout/GridList/index.tsx
> +        {items.concat().map((item, index, arr) => (
concat은 왜 했더라..? 이유가 있었던 거 같은데...

2020-04-21 13:17 UTC, chiabi commented on src/layout/GridList/index.tsx
> +        {items.concat().map((item, index, arr) => (
ReadonlyArray 때문에 넣었었담

2020-04-21 13:17 UTC, chiabi commented on src/layout/GridList/index.tsx
>    margin-left: -12px;
호호호 여기때문에 컨테이너가 필요한 거였던 거임ㅋㅋㅋㅋ @cheolee 
커밋 하나 취소하고 다시 수정해야겠담

2020-04-21 13:19 UTC, chiabi commented on src/layout/GridList/index.tsx
> +  renderItem: (item: T, index: number, arr: T[]) => ReactElement;
혹시...몰라서???? 넣기는 했는데 나중에 필요하다고 하면 넣을까?

2020-04-21 13:22 UTC, chiabi commented on src/layout/GridList/index.tsx
> +        {items.concat().map((item, index, arr) => (
```
This expression is not callable.
  Each member of the union type '(<U>(callbackfn: (value: T, index: number, array: readonly T[]) => U, thisArg?: any) => U[]) | (<U>(callbackfn: (value: T, index: number, array: T[]) => U, thisArg?: any) => U[])' has signatures, but none of those signatures are compatible with each other.
```

2020-04-21 13:22 UTC, cheolee commented on src/layout/GridList/index.tsx
> +        {items.concat().map((item, index, arr) => (
이거, map 함수를 만들면 어떨까?
```
function mapArray<T>(
  arr: T[] | ReadonlyArray<T>,
  callback: typeof Array.prototype.map<T>   // 이거 이렇게 될지 모르겠음.. 암튼 Array.map 을 가져와서 타이핑...
) {
  return (arr as any as T[]).map(callback);
}
```

이런...느낌...

이것도 예전에 시도해봤던 거 같기도 하고...

2020-04-21 13:27 UTC, cheolee commented on src/layout/GridList/index.tsx
>    margin-left: -12px;
아하... Item 패딩 때문이구만...? 이거 이런 식으로 하면 되기는 하는데

```
const ~~~ = styled.li<{numberOfColumns: number}>`
  &:nth-child(${numberOfColumns}n + ${numberOfColumns - 1}) {
    margin-left: 24px;
  }
`
```
(제대로 쓴 건지는 모르겠음)

2020-04-21 13:29 UTC, cheolee commented on src/layout/GridList/index.tsx
>    margin-left: -12px;
아, 이게 맞겠다
```
const ~~~ = styled.li<{numberOfColumns: number}>`
  &:not(:nth-child(${props => props.numberOfColumns}n)) {
    margin-left: 24px;
  }
`
```

2020-04-21 13:29 UTC, cheolee commented on src/layout/GridList/index.tsx
> +  renderItem: (item: T, index: number, arr: T[]) => ReactElement;
응!! 빼자!!
어채피 items는 밖에서도 알고 있는 녀석이라 필요없을듯!

2020-04-21 13:36 UTC, chiabi commented on src/layout/GridList/index.tsx
> +        {items.concat().map((item, index, arr) => (
근데 저기가 유니온 아니고 ReadonlyArray 여도 문제가 없을 것 같은데 흠

2020-04-21 13:39 UTC, sim-zi reviewed
https://github.com/pedaling/class101-ui/pull/235#discussion_r412175883

여기다가 코멘트 달아버려써

2020-04-22 03:17 UTC, chiabi commented on src/layout/GridList/index.tsx
>    margin-left: -12px;
이게 grid를 사용하지 않고 flex를 이용해서 구현하려다 보니 생기는 문제인데

`calc(100% - (gap * (column - 1)) / column)`이런식으로 중첩 calc 문을 이용해서 column의 width를 구할 수 있는데, 이렇게 구할 경우 `not(:nth-child~) { margin-left: gap }`이 가능함.
근데 이 중첩 calc문이 ie11에 이슈가 있다고 해서 이를 피하려고 
column의 width를 구할 때 `100 / column`으로 하고 `box-sizing: border-box;`와 padding-left, right를 이용해서 이 gap을 뺀 만큼의 width를 contents width를 가지게 했음

그래서 요거 좀 고민이네 @cheolee

2020-04-22 05:15 UTC, cheolee commented on src/layout/GridList/index.tsx
>    margin-left: -12px;
원복!!!

2020-04-22 05:15 UTC, sim-zi approved these changes
lgtm!!!
감사합니다!!!

2020-04-22 06:42 UTC, iseongho approved these changes

2020-04-22 07:53 UTC, chiabi commented
리뷰 땡큐~~~~~🥺

2020-04-22 08:49 UTC, merged