feat: Paper 컴포넌트를 추가한다
pedaling/class101-ui pull request #25
Opened 2019-03-05 03:20 UTC by chiabi

2019-03-05 04:19 UTC, bae-unidev requested changes

2019-03-05 04:19 UTC, bae-unidev commented on src/Paper/index.tsx
> +  border-radius: ${props => props.borderRadius || 1}px;
이거 이렇게 쓰면 안될 것 같애. 0을 주는 경우에 가드땜에 1되어버려서..

2019-03-05 04:19 UTC, bae-unidev commented on docs/components/Paper.tsx
> +  /** 모바일(sm)에서 차지할 열 */
이거 주석 잘못되었어

2019-03-05 05:33 UTC, sim-zi requested changes

2019-03-05 05:33 UTC, sim-zi commented on src/ElevationStyle/index.tsx
> +export const elevationStyles = {
변수명을 지을 때 복수형은 보통 array의 이름을 지을 때 써서, 여기는 elevation value와 style의 key-value map 형태이니까 변수 이름을 `{value}By{key}` 형태로 이름을 지어주면 좋겠어!
여기서는 `elevationStyleByElevation` 라고 하면 될듯

그래서 쓸 때는

```
const elevationStyle = elevationStyleByElevation[1];
```

이런 식으로 돼서, 변수 이름으로 어떤 구조의 데이터인지 알 수 있고 가독성도 좋아져!

2019-03-05 05:33 UTC, cheolee commented on src/ElevationStyle/index.tsx
> +
```
type ElevationValue = 1 | 2 | 3 | 4 | 5;
```

이런 타입을 만들어주면 좋겠다

2019-03-05 05:33 UTC, cheolee commented on src/ElevationStyle/index.tsx
> +  elevation?: 1 | 2 | 3 | 4 | 5;
```
elevation?: ElevationValue;
```
위에서 만든 타입을 사용해서~

2019-03-05 05:33 UTC, cheolee commented on src/ElevationStyle/index.tsx
> +export const elevationStyles = {
```
const elevationStyles: { [key in ElevationValue]: FlattenSimpleInterpolation }
```

이렇게 타입을 지정해주면 더욱 type-safe 할듯!

2019-03-05 05:33 UTC, cheolee commented on src/Paper/index.tsx
> +  border-radius: ${props => props.borderRadius || 1}px;
이런 경우가 잦아서 보통 null, undefined 가드하는 함수를 만드는데, lodash에 그런 역할을 하는 `defaultTo()`가 있어서 얘를 쓰면 좋을 듯
https://lodash.com/docs/4.17.11#defaultTo

2019-03-05 05:33 UTC, cheolee commented on src/Paper/index.tsx
> +  ${props => elevationStyles[props.elevation === undefined ? 4 : props.elevation]}
여기도 defaultTo로 쓰면 가독성이 좋겠다

2019-03-05 05:33 UTC, cheolee commented on src/Paper/index.tsx
> +export default class Paper extends PureComponent<PaperProps & HTMLDivProps> {
Props에 HTMLDivProps 를 두면 docz에서 prop table이 엄청 길어지지는 않남?!
요거 저번에 호이랑 셋이 있을 때 잠깐 했던 얘긴데,
```
interface Props {
  ...
  containerDivAttributes?: HTMLDivProps;
}

...

public render() {
  ...
  return (
    <Container elevation={elevation} {...containerDivAttributes}>
      ...
  )
}
```

이런 식으로, html element에 대한 prop은 따로 필드를 둬서 받는 거 어때?

이러면 prop table도 짧아지고 컴포넌트 내부에 root 뿐만 아니라 여러 엘리먼트들에 기본 html 속성들을 줄 필요가 있는 경우에도 필드만 추가하면 되니까 유용할 듯

2019-03-05 05:34 UTC, sim-zi requested changes

2019-03-05 05:34 UTC, cheolee commented on src/ElevationStyle/index.tsx
> +export const elevationStyles = {
그리고 file scope constant니까 UPPER_CASE로 써줘야할듯!

2019-03-05 07:12 UTC, chiabi commented on src/Paper/index.tsx
> +export default class Paper extends PureComponent<PaperProps & HTMLDivProps> {
지금 구조에서는 docz에 prop으로 따로 명시해줘야 테이블에 노출되고 있긴 함

그럼 위에 처럼 구분해서 필드를 받으면 
```
<Paper
borderRadius={2}
elevation={1} 
containerDivAttributes={{
  id: 'section_id',
  className: 'section_class',
  tabIndex: 1
}} />
```
이런 식으로 써야되는 거지?? 요렇게 명시적으로 구분하는 게 더 나은 건가?

2019-03-05 07:23 UTC, cheolee commented on src/Paper/index.tsx
> +export default class Paper extends PureComponent<PaperProps & HTMLDivProps> {
응 나는 저렇게 명시적으로 구분하는 게 좋다고 생각하는데, 가장 중요한 이유는 두 가지

1. html element attribute와 새로 정의한 prop의 이름이 같을 경우 충돌이 일어남
예를 들어서, input element의 경우에는 type이라는 attribute가 있는데, 새로 정의한 prop에서도 type이라는 이름으로 prop을 만들면 충돌이 일어나게 됨
기본적으로 존재하는 attribute는 생각보다 많으므로 예기치 않은 충돌을 막으려면 별도로 분리하는 쪽이 좋음

2. 컴포넌트 내의 여러 엘리먼트들에 대해서 속성을 지정해줘야 하는 경우에 하위호환을 지키기 어려움

만약 `<Paper id='section_id' />` 이렇게 쓰고 있었는데, Paper 내의 다른 엘리먼트에도 id를 넣어줘야하는 일이 생긴다면 `<Paper id='section_id' otherId='other_id' />` 이런 식으로 쓰게 됨.
미리 나눠두면 하위호환을 지키기 쉬움



그 외에도 docz에서 굳이 prop 노출용 컴포넌트를 따로 만들지 않아도 돼서 좋음 (노출용 컴포넌트를 만드는 게 source of truth 를 어기는 거라 없앨 수 있으면 없애는 게 좋은 듯..!)

2019-03-05 07:28 UTC, chiabi commented on src/Paper/index.tsx
> +export default class Paper extends PureComponent<PaperProps & HTMLDivProps> {
오호 굳굳

2019-03-05 13:05 UTC, bae-unidev approved these changes

2019-03-05 13:05 UTC, sim-zi requested changes

2019-03-05 13:05 UTC, cheolee commented on src/Paper/index.tsx
> +import defaultTo from '../utils/defaultTo';
이거, 따로 만드는 것보다는 lodash꺼 쓰는 게 좋을 듯!!

lodash 라이브러리가 아직 없다면 `yarn add lodash-es` 하면 될듯!!

2019-03-05 13:07 UTC, sim-zi requested changes

2019-03-05 13:07 UTC, cheolee commented on src/Paper/index.tsx
> +  public defaultProps = {
defaultProps 혹시 요거 작동하고 있어?!
얘는 static으로 써줘야됑

```
public static defaultProps = { ... };
```

요렇게!!

그리고 혹시 static defaultProps 에 마우스 커서 올렸을 때 제대로 타이핑이 나오는지 확인해조

2019-03-06 03:20 UTC, chiabi commented on src/Paper/index.tsx
> +  public defaultProps = {
👌 요거 확인함~

2019-03-06 04:01 UTC, bae-unidev commented
이 컴포넌트 디자인 팀이랑 Paper라고 부르기로 정한거지?

2019-03-06 05:10 UTC, chiabi commented
Card는 이미 있어서 머테리얼 디자인 참고해서 짓기는 했는데 쿤이랑 얘기해봐야겠다

2019-03-06 10:59 UTC, chiabi commented
Paper 컴포넌트에 대해 쿤이랑 얘기를 해봤는데 나중에 좀 더 명확해지면 추가하기로 하고 elevation 스타일만 쓸 수 있게 바꿨음다. 😢

2019-03-06 13:31 UTC, sim-zi requested changes
글쿤..!

2019-03-06 13:31 UTC, cheolee commented on docs/styles/Elevation.tsx
> +export const Elevation1 = styled.div`
요거 1,2,3,4,5가 각각 컴포넌트가 있는 것보다는 prop으로 받는 쪽이 유지보수하기 좋지 않을까?!

2019-03-08 12:17 UTC, sim-zi approved these changes

2019-03-08 12:17 UTC, cheolee commented on docs/styles/ElevationStyles.mdx
> +  <Elevation elevation={1}>elevation1</Elevation>
이렇게 docs용으로 Elevation 컴포넌트를 만들면 문서로만 봐서는 어떻게 사용하는지 알 수 없으니, docs/styles/Elevation.tsx 는 만들지 말구 elevation1, elevation2 같은 걸 사용하는 모습을 Playground로 보여주는 게 더 좋을 것 같은디 아직 이 아이들은 정식 컴포넌트가 아니니 일단 이렇게 합시당~~

2019-03-11 02:56 UTC, merged