feat: Reply 컴포넌트 추가
pedaling/class101-ui pull request #269
Opened 2020-06-10 08:24 UTC by SeoziMadeInKorea

기존의 Comment 컴포넌트가 Reply로
대댓글이 Comment로 바뀜에 따라 컴포넌트를 새로 개발했습니다

![image](https://user-images.githubusercontent.com/30362922/84244651-eb2ae380-ab3e-11ea-83ca-b938ff89d83b.png)

2020-06-11 04:33 UTC, tbvjaos510 requested changes

2020-06-11 04:33 UTC, tbvjaos510 commented on src/components/Reply/Action/index.tsx
> +  ${BreakPoints.media.sm``}
지워도 될듯!

2020-06-11 04:33 UTC, tbvjaos510 commented on src/components/Reply/Content/index.tsx
> +  }, [contentRef, children]);
```suggestion
  }, [children]);
```
ref는 항상 최신 값을 가지고 있어서 deps에 안들어가도 될듯!

2020-06-11 04:41 UTC, chiabi commented on src/components/Badge/index.tsx
> -
<img width="389" alt="스크린샷 2020-06-11 오후 12 36 52" src="https://user-images.githubusercontent.com/15900134/84342336-4cef5a00-abe0-11ea-9a9e-d9a0ccddaa38.png">

뱃지는 Reply외에도 쓰이는 컴포넌트라 사이즈별 패딩이 있어야하는데 해당 부분을 지우면 뱃지가 틀어집니다😢 확인해주세요.

2020-06-11 04:41 UTC, chiabi commented on src/components/Reply/Action/index.tsx
> +  ${BreakPoints.media.sm``}
사용하지 않는다면 지워주세용

2020-06-11 04:41 UTC, chiabi commented on src/components/Reply/Action/index.tsx
> +    `};
> If you're interpolating a string you do not need to use this, only if you're interpolating a function.
(https://styled-components.com/docs/api#css)

문자열만 interpolating하는 경우 css helper function을 사용하지 않아도 됩니다
(45, 50, 55줄 동일)

2020-06-11 04:41 UTC, chiabi commented on src/components/Reply/index.tsx
> +import { gray500, gray800, orange500 } from 'core/Colors';
상대경로를 안쓰면 빌드할 때 에러가 날거에요😢

2020-06-11 04:41 UTC, chiabi commented on src/components/Reply/Content/index.tsx
> +import { body2 } from 'core/TextStyles';
상대경로를 안쓰면 빌드할 때 에러가 날거에요😢

2020-06-11 04:41 UTC, chiabi commented on src/components/Reply/index.tsx
> +  color: ${props => props.color};
Caption2가 color props를 받기 때문에 해당 줄은 없어도 될 것 같음다

2020-06-11 04:41 UTC, chiabi commented on src/components/Reply/index.tsx
> +      name = '서지',
default name 빼주세용

2020-06-11 04:43 UTC, chiabi commented
Comment랑 중복되는 컴포넌트 같은데 Comment를 제거하는게 어떨까요?
번들 사이즈를 줄입시당

2020-06-11 04:44 UTC, SeoziMadeInKorea commented on src/components/Badge/index.tsx
> -
확인 후 수정했습니당

2020-06-11 04:54 UTC, SeoziMadeInKorea commented
> Comment랑 중복되는 컴포넌트 같은데 Comment를 제거하는게 어떨까요?
> 번들 사이즈를 줄입시당

지금 Comment를 사용하는 곳이 많을텐데 전부 수정되고 제거하는게 어떨까요??

2020-06-11 05:06 UTC, SeoziMadeInKorea commented on src/components/Reply/Action/index.tsx
> +  ${BreakPoints.media.sm``}
확인 후 수정했습니당

2020-06-11 05:06 UTC, SeoziMadeInKorea commented on src/components/Reply/Action/index.tsx
> +    `};
확인 후 수정했습니당

2020-06-11 05:06 UTC, SeoziMadeInKorea commented on src/components/Reply/Content/index.tsx
> +import { body2 } from 'core/TextStyles';
확인 후 둘 다 수정했습니당

2020-06-11 05:06 UTC, SeoziMadeInKorea commented on src/components/Reply/index.tsx
> +  color: ${props => props.color};
확인 후 수정했습니당 감사합니당

2020-06-11 05:06 UTC, SeoziMadeInKorea commented on src/components/Reply/index.tsx
> +      name = '서지',
확인 후 수정했습니당

2020-06-11 05:07 UTC, SeoziMadeInKorea commented on src/components/Reply/Content/index.tsx
> +  }, [contentRef, children]);
확인 후 둘 다 수정했습니당

2020-06-11 08:19 UTC, chiabi commented
오우 바로 마이그레이션 진행하지 않는 건가요???

2020-06-12 01:36 UTC, moodselah commented on src/components/Reply/Action/index.tsx
> +`;
`IconButton` 대신 `Icon`을 사용하고 cursor는 부모에서 컨트롤하는게 좋을 것 같아요!

2020-06-12 01:36 UTC, moodselah commented on src/components/Reply/Content/index.tsx
> +  -webkit-box-align: baseline;
```suggestion
  display: box;
  box-align: baseline;
```
요렇게 쓰면 autoprefixer같은게 prefix같은거 안달아주려낭?? cc. @chiabi 
ui에 설정이 안되있으려남

2020-06-12 01:36 UTC, moodselah commented on src/components/Reply/index.tsx
> +              leftAction.map((action, key) => React.cloneElement(action, { position: ButtonIconPosition.LEFT, key }))}
```suggestion
            {leftAction?.map((action, key) => React.cloneElement(action, { position: ButtonIconPosition.LEFT, key }))}
```

2020-06-12 01:36 UTC, moodselah commented on src/components/Reply/index.tsx
> +              rightAction.map((action, key) => React.cloneElement(action, { position: ButtonIconPosition.RIGHT, key }))}
```suggestion
            {rightAction?.map((action, key) => React.cloneElement(action, { position: ButtonIconPosition.RIGHT, key }))}
```

2020-06-12 06:24 UTC, SeoziMadeInKorea commented
> 오우 바로 마이그레이션 진행하지 않는 건가요???

넹넹 천천히 마이그레이션 할 것 같슴다

2020-06-12 16:33 UTC, john015 commented on src/components/Reply/Content/index.tsx
> +  -webkit-box-align: baseline;
요거 styled-components의 css pre-processor인 stylus에서 auto-prefix 붙여주는걸로 알아
https://github.com/stylus/stylus

2020-06-15 07:56 UTC, chiabi commented on src/components/Reply/Content/index.tsx
> +  -webkit-box-align: baseline;
styled-component가 autoprefixer를 지원하긴 하는데
> **Automatic vendor prefixing:** write your CSS to the current standard and let styled-components handle the rest.
You get all of these benefits while still writing the CSS you know and love, just bound to individual components.

autoprefixer에서 접두사를 붙이지 않는 예외의 경우가 몇가지 있음다.
👉 https://github.com/postcss/autoprefixer/issues/1014

<img width="393" alt="스크린샷 2020-06-15 오후 4 16 54" src="https://user-images.githubusercontent.com/15900134/84631764-e42e1780-af28-11ea-9947-19b795f4fc39.png">

2020-06-15 09:21 UTC, moodselah commented on src/components/Reply/Content/index.tsx
> +  -webkit-box-align: baseline;
호웃..😥

2020-06-17 02:39 UTC, tbvjaos510 approved these changes

2020-06-17 02:41 UTC, chussum approved these changes

2020-06-17 02:42 UTC, merged