fix: tab 컴포넌트를 추가한다
pedaling/class101-ui pull request #30
Opened 2019-03-21 07:06 UTC by chiabi

2019-03-21 08:56 UTC, iseongho commented
fix요?

2019-03-21 09:10 UTC, chiabi commented
으아니

2019-03-21 10:00 UTC, bae-unidev requested changes

2019-03-21 10:00 UTC, bae-unidev commented on src/Tab/TabContainer.tsx
> +  title: string;
이거 우리 지금 디자인에 탭 제목 옆에 붙는 addon 어케 할지 쿤이랑 이야기 해본적 있남? 뱃지나, 작은 텍스트가 탭 제목 옆에 들어갈 수 있는걸 고려해야할듯?

2019-03-21 10:05 UTC, sim-zi requested changes

2019-03-21 10:05 UTC, cheolee commented on src/Tab/TabContainer.tsx
> +            flexBasis={fluid ? 'auto' : `${100 / tabs.length}%`}
TabItem로 fluid를 그대로 넘겨줍시당
여기서 flexBasis로 해석해서 넘기면, TabItem내부에서 flexBasis에 따라 분기가 생기는 부분
(https://github.com/pedaling/class101-ui/pull/30/files#diff-0aecf1d41b5fb8b7e7d3d313d0b244d8R51)
에서 왜 'auto'에 대해 이런 처리를 해야하는지 이해하기 어려워집니다.
TabItem에 fluid를 그대로 넘긴다면 TabItem 안에서 fluid에 맞는 css를 렌더링한다는 뜻을 더 이해하기 쉬워지겠쭁!

2019-03-21 10:05 UTC, sim-zi commented on src/Tab/TabContainer.tsx
> +  htmlDivAttributes?: HTMLAttributes<HTMLUListElement>;
간결하게 html 을 생략하고 divAttributes 라고 써도 좋을 것 같슴다!!

2019-03-21 11:00 UTC, chiabi commented on src/Tab/TabContainer.tsx
> +  title: string;
요거 쿤이랑 얘기했는데 뱃지가 들어가는 디자인은 현재 앱에만 있어서 웹에는 필요없지만, 들어갈 수도 있다고 합니다. 뱃지 컴포넌트도 정리되어야 할 것 같아서 같이 수정하겠음

2019-03-21 11:35 UTC, bae-unidev commented on src/Tab/TabContainer.tsx
> +  title: string;
이미 웹에 커뮤니티 게시물 갯수 표시하는 게 있지 않어?

이 repo의 컴포넌트들은 디자인 가이드기도 하지만, 웹의 중복 컴포넌트 코드를 DRY하게 리펙터링 하는 목표도 있습니다. 웹에 쓰이는 모든 탭 컴포넌트의 인터페이스를 커버하지 못하면 여기 만들어도 또 다른 파생 컴포넌트/스타일이 나와서 결국엔 같은 작업을 또 하게 되지 않을까?

2019-04-02 05:14 UTC, chiabi commented on src/Tab/TabContainer.tsx
> +  title: string;
이 코드에서 커뮤니티 게시물 갯수 표시되는 걸 badge로 받게했는데 이거 말고 class101/ui에 Badge컴포넌트도 들어갈 수 있어야 한다고 해서 관련해서 수정하겠음

2019-05-28 12:33 UTC, chiabi commented
diff가 커져서 죄송합니다😢mdx는 뷰 확인을 위해 불가피했어요...

2019-05-28 12:33 UTC, bae-unidev commented
class101-web에 components/Tabs를 한번 볼래? API를 이런식으로 바꾸는게 좋을 것 같음. blueprintjs를 참고한건데, 탭은 panel이랑 항상 붙어있게 하는게 좋을것 같아. 아니면 그냥 Button을 Group으로 묶어서 쓰는거랑 별반 다르지 않을 것 같애.

```
export default class Tabs<T extends string = string> extends Component<Props<T>> {
  public static Item = TabItem;
...
}
```
```
<Tabs<PromotionMenu> value={this.currentTab} onChange={this.handleChangeTab}>
  <Tabs.Item value={PromotionMenu.ISSUE} panel={<IssueCouponPanel promotionStore={promotionStore} />} />
  <Tabs.Item value={PromotionMenu.ANALATICS} panel={<AnalyticsPromotionPanel promotionId={promotionId} />} />
</Tabs>
```

Tab와 Tabs.Item, panel이 핵심! 그리고 Tabs를 생성할 때 value를 제네릭으로 타이핑을 하는 부분도 같이 봐주셈!

2019-05-28 12:34 UTC, chiabi commented on docs/HelpComponents.tsx
> +export default {};
docs에서 사용할 dark 테마 컴포넌트용 검은 배경입니다.

2019-05-28 12:35 UTC, chiabi commented on docs/components/Tab.tsx
> +};
안 만들려고 했는데 withTheme같은 HOC로 한번 감싸면 docz PropsTable에서 읽어내질 못해서 문서용으로 추가했어요

2019-05-28 13:20 UTC, sim-zi requested changes

2019-05-28 13:20 UTC, cheolee commented on docs/HelpComponents.tsx
> +export default {};
default export가 필요한가융

2019-05-28 13:20 UTC, cheolee commented on docs/components/Tab.tsx
> +interface Props {
이 props를 새로 만들지 말구 @class101/ui 에 있는 걸 사용해서 만들 수 있을까융?
원본 컴포넌트의 prop과 여기있는 prop이 유리될 수 있을 것 같은 코드스멜이 느껴집니당

2019-05-28 13:20 UTC, cheolee commented on src/Tab/index.tsx
> +export default withTheme(Tab);
`withTheme()` 대신 `<ThemeProvider>`를 이용해서 구현할 수 있을까유? 그러면 docz에서 따로 컴포넌트 안 만들어도 될 거 같아용!

e.g. https://www.styled-components.com/docs/advanced#theming

2019-05-28 13:20 UTC, cheolee commented on src/Tab/index.tsx
> +              className={`${className ? `${className}-item ` : ''}${tab.value === currentValue ? 'active' : ''}`}
active의 경우에는 prop으로 넘겨주고, TabItem내에서 styled-component로 스타일 분기를 처리하면 좋을 것 같습니다.
className은 string이기 때문에, 이 라인에서의 코드와 TabItem내의 스타일 코드에서 active라는 클래스 이름을 항상 맞춰줘야하기 때문에 실수가 일어나기 쉽습니당

`${className}-item` 는 어디에서 사용되나요?!

```suggestion
              active={tab.value === currentValue}
```

2019-05-29 01:45 UTC, chiabi commented on src/Tab/index.tsx
> +export default withTheme(Tab);
styled로 만든 컴포넌트가 아닐경우 withTheme()를 사용해야 상위 ThemeProvider로부터 theme를 내려받을 수 있음;;

2019-05-29 01:45 UTC, chiabi commented on src/Tab/index.tsx
> +              className={`${className ? `${className}-item ` : ''}${tab.value === currentValue ? 'active' : ''}`}
요거는 조이의 코멘트를 참고해서 수정할 예정입니당

2019-05-29 02:23 UTC, chiabi commented on docs/components/Tab.tsx
> +interface Props {
docz 0버전을 사용하고 있어서 불가피할 것 같아요 tab까지 이렇게 사용하고 docz v1에선 해결되었는지 버전을 올릴 수 있는지 알아볼게용

2019-05-29 03:38 UTC, iseongho commented on docs/HelpComponents.tsx
> +export default {};
필요하다면 왜 object를 선택하셨죵?

2019-05-29 03:38 UTC, iseongho commented on src/Tab/index.tsx
> +  children?: ReactNode;
children은 타이핑 안해도 되지 않음?

2019-05-29 03:38 UTC, iseongho commented on src/Tab/index.tsx
> +    color: ${props => getTabActiveColorByTheme(props.theme)[props.type]};
이거 해석하기 난해한 거 같은데 ㅋㅋㅋ
props.theme랑 props.type 둘 다 스타일에 관련된 친구들 아님??

그리고 ByTheme인데 왜 ByType같지

2019-05-29 04:04 UTC, chiabi commented on docs/HelpComponents.tsx
> +export default {};
이거 예전에 default export가 없다고 lint에 걸린 기억이 남아서 넣은 건데 없어도 이상이 없어서 수정했어요

2019-05-29 04:07 UTC, chiabi commented on src/Tab/index.tsx
> +    color: ${props => getTabActiveColorByTheme(props.theme)[props.type]};
theme를 인자로 받아서 출력하는 거라 ByTheme라고 했지만 인자로도 충분히 유추할 수 있어서 getTabBorderColor, getTabActiveColorByType으로 수정하겠음

2019-05-29 04:19 UTC, cheolee commented on docs/components/Tab.tsx
> +interface Props {
오호... 타입 가져오는 것도 안 되나보군용... ㅜㅜ

2019-05-29 04:20 UTC, cheolee commented on src/Tab/index.tsx
> +              className={`${className ? `${className}-item ` : ''}${tab.value === currentValue ? 'active' : ''}`}
다음 pr에서 수정되나욥?

2019-05-29 04:27 UTC, cheolee commented on src/Tab/index.tsx
> +export default withTheme(Tab);
글쿤용...
우리 이제 앞으로 theme 기능으로 스타일링 하는 건가유?

2019-05-29 04:36 UTC, iseongho approved these changes

2019-05-29 04:45 UTC, hrg921 commented on src/Tabs/index.tsx
> +    this.props.onChange(value as T);
```suggestion
    const { onChange, value } = this.props;
    this.props.onChange(value as T);
```

2019-05-29 04:45 UTC, hrg921 commented on src/Tabs/index.tsx
> +      throw new Error('이 컴포넌트는 controlled 하게만 사용 가능합니다.');
controlled 하다는게 뭔뜻인가용 ?.?

2019-05-29 04:45 UTC, hrg921 commented on src/index.ts
> +// TODO: docz v1로 올리고 PropsTable용 Tabs named export를 제거한다
```suggestion
// TODO(chiabi): docz v1로 올리고 PropsTable용 Tabs named export를 제거한다
```

2019-05-29 04:45 UTC, hrg921 commented on src/index.ts
> +// TODO: docz v1로 올리고 PropsTable용 Tabs named export를 제거한다
치치의 투두가 아닌 것인가용?.?

2019-05-29 04:45 UTC, hrg921 commented on src/Tabs/TabItem.tsx
> +  flex-basis: ${props => (props.fluid ? 'auto' : `${100 / props.indicatorCount}%`)};
fluidTabBoxStyle과 같은 변수를 하나 만드는 건 어떨까요

```typescript
const fluidTabBoxStyle = css``
```

2019-05-29 04:45 UTC, hrg921 commented on src/Tabs/TabItem.tsx
> +  flex-basis: ${props => (props.fluid ? 'auto' : `${100 / props.indicatorCount}%`)};
active도 마찬가지로 처리해서 분기처리가 한 플래그 변수에 대해 한번만 일어나는게 좋은 것 같아용

2019-05-29 06:06 UTC, bae-unidev commented on src/Tabs/index.tsx
> +      throw new Error('이 컴포넌트는 controlled 하게만 사용 가능합니다.');
https://reactjs.org/docs/uncontrolled-components.html 이 문서를 참고하면 됩니다!

2019-05-29 06:08 UTC, bae-unidev approved these changes

2019-05-29 06:17 UTC, hrg921 commented on src/Tabs/index.tsx
> +      throw new Error('이 컴포넌트는 controlled 하게만 사용 가능합니다.');
해당 링크를 에러에 포함시키는 것은 안티패턴일까요?

2019-05-29 06:44 UTC, chiabi commented on src/index.ts
> +// TODO: docz v1로 올리고 PropsTable용 Tabs named export를 제거한다
사실 ui의 투두는 나의 투두라서 안 달긴 했음ㅋㅋㅋㅋㅠㅠㅠ

2019-05-30 07:44 UTC, chiabi commented
```
(alias) const Tabs: React.ForwardRefExoticComponent<Pick<Props<string>, "onChange" | "value" | "fluid" | "className" | "type"> & {
    theme?: any;
}>
import Tabs
JSX element type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | any | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)> | null' is not a constructor function for JSX elements.
  Type 'null' is not assignable to type 'ElementClass'.ts(2605)
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)
```
```
Property 'Item' does not exist on type 'ForwardRefExoticComponent<Pick<Props<string>, "value" | "className" | "onChange" | "type" | "fluid"> & { theme?: any; }>'.ts(2339)
```
Tab를 withTheme로 감쌌을 때 web에서 ts lint에 위와 같이 에러가 발생해서 ThemeProvider를 통해서 테마를 받을 수 있는 방법은 다른 방법을 생각해보겠습니다.

2019-05-30 08:06 UTC, hrg921 approved these changes

2019-05-30 08:06 UTC, hrg921 commented on src/Tabs/TabItem.tsx
> +const TabBox = styled.div<TabBosProps>`
const fluidTabBoxStyle = css``
이런식으로 빼는건 별로일까요..?

2019-05-30 08:31 UTC, chiabi commented on src/Tabs/TabItem.tsx
> +const TabBox = styled.div<TabBosProps>`
음 그러면 fluidTabBoxStyle, solidTabBoxStyle 이렇게 변수를 두개 만들어야 할 텐데 
그렇게 TabBox 바깥으로 별도의 변수들을 만들어 빼내는게 더 전체 style을 읽기 편하다고 우리끼리 얼라인이 맞춰진다면 제안한대로 리팩토링 되어도 좋을 것 같아요

2019-05-30 08:34 UTC, iseongho approved these changes

2019-05-30 10:22 UTC, chiabi commented on src/Tabs/TabItem.tsx
> +const TabBox = styled.div<TabBosProps>`
```js
const TabBox = styled.div<TabBoxProps>`
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 14px 4px 13px 4px;
  ${props =>
    props.fluid
      ? `
    flex-basis: auto;
    margin-right: 26px;
    `
      : `
    flex-basis: ${100 / (props.indicatorCount || 1)}%;
    margin-right: 0;
    `};
```
```js
const fluidTabBoxStyle = css`
  flex-basis: auto;
  margin-right: 26px;
`;

const solidTabBoxStyle = (indicatorCount?: number) => css`
  flex-basis: ${100 / (indicatorCount || 1)}%;
  margin-right: 0;
`;

const TabBox = styled.div<TabBoxProps>`
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 14px 4px 13px 4px;
  ${props => (props.fluid ? fluidTabBoxStyle : solidTabBoxStyle(props.indicatorCount))};
```

2019-05-30 10:28 UTC, ddalpange commented on src/Tabs/TabItem.tsx
> +const TabBox = styled.div<TabBosProps>`
저는 돔트리든 css든 길어도 상관없으니 하나의 흐름으로 읽었으면 좋겠어용 :)

2019-05-30 12:16 UTC, merged