WIP refactor: v7
pedaling/class101-ui pull request #53
Opened 2019-05-09 10:38 UTC by bae-unidev

2019-05-09 10:52 UTC, chiabi commented
오호 좋심다 package.json에 Icon generate하는 거 path 같이 수정해주세용

2019-05-09 11:37 UTC, bae-unidev commented
이거 내가 now쪽으로 deploy하는것도 같이 작업할게, ui.class101.dev 로 alias 설정할게

2019-05-09 13:44 UTC, bae-unidev commented
MEMO: Circular dependency 해결하고 폴더구조 정리, module alias 설정하기

2019-05-16 03:23 UTC, chiabi approved these changes

2019-05-16 11:20 UTC, chiabi commented
요거 머지하고 배포 작업해도 되나용?

2019-05-16 11:21 UTC, chiabi commented
아 now가 남았나?

2019-05-16 12:04 UTC, chiabi requested changes
docz에서 layout 페이지에서 에러 확인해주세용

2019-05-16 12:11 UTC, bae-unidev commented
ㄴㄴ 아직 아냐 이거 순환참조 문제가 있어서 그거 해결하고 WIP 뗄게!

2019-05-16 15:11 UTC, bae-unidev commented
이 PR은 닫고 monorepo를 더 배우고 오겠습니다... 괜히 lerna 붙히고 깝쳤다가 프로젝트를 거의 엎어놨습니다..

2019-05-16 15:11 UTC, closed without merging

2019-05-17 12:56 UTC, chiabi commented
😢