feat: callout 컴포넌트를 추가한다
pedaling/class101-ui pull request #66
Opened 2019-06-23 08:22 UTC by chiabi

https://www.figma.com/file/BPv3p1SEYUKhuKyYW3syfTgq/Class101_Web%2FApp?node-id=1557%3A581

2019-06-23 08:50 UTC, ddalpange requested changes

2019-06-23 08:50 UTC, ddalpange commented on src/components/Callout/index.tsx
> +  action?: ActionProps;
CallOut은 Action이 하나만 되도록 정해진걸까? 여러개를 받아야 할 것 같은데

2019-06-24 03:02 UTC, chiabi commented on src/components/Callout/index.tsx
> +  action?: ActionProps;
액션 하나만 들어가는 걸로 얘기했는데 만약 나중에 액션이 하나 더 들어가야할 필요성을 느낀다면 secondaryAction으로 추가하면 될 듯!

2019-06-24 03:04 UTC, ddalpange approved these changes
죠아용~

2019-06-24 03:10 UTC, merged