feat/create-datapicker DataPicker 컴포넌트 추가
pedaling/class101-ui pull request #89
Opened 2019-08-19 12:05 UTC by tbvjaos510

datapicker 컴포넌트를 추가했습니다

## Image
![image](https://user-images.githubusercontent.com/32216112/63263926-d128c780-c2c4-11e9-8575-517d34fe2a3d.png)

2019-08-19 12:12 UTC, chiabi commented
빌드 실패하는데 로컬에서 yarn build 함 해봐줄래요?

2019-08-20 01:40 UTC, tbvjaos510 commented
수정했어요!

2019-08-20 05:54 UTC, chiabi commented
이거 시간을 range로 조절하는 ui는 고민이 더 필요할 것 같습니다
1분 단위로 조절한다고 하면 불편할 수 있을 것 같음

이거는 문서에서 개발 중으로 표시하고 component/ 가 아니라 dev 같은 개발용 메뉴를 만들어 옮기거나 문서를 숨기는 게 좋을 것 같아요

그리고 디자이너와 같이 얘기해봐야할 것 같습니당

2019-09-05 05:07 UTC, ddalpange requested changes
계속 알람이 와서 상태 수정해두겠슴당
다되면 리뷰어 다시 걸어조 ㅎㅎ

2019-09-16 11:36 UTC, tbvjaos510 commented
* 충돌을 해결하기 위해 rebase를 하나의 커밋으로 합쳤습니다.
* TimeSelector 삭제
* RangePicker기능 추가

### Image
![image](https://user-images.githubusercontent.com/32216112/64954800-9749e180-d8c1-11e9-9706-a382b75a7f33.png)

2019-09-17 05:45 UTC, ddalpange requested changes
handleBtnClick (x)
handleClickBtn (o)
이런식으로 동사명사 순서를 맞춰주십숑!
만드느라 고생했어어

2019-09-17 05:45 UTC, ddalpange commented on src/formInputs/DatePicker/MonthCalendar/Day/index.tsx
> +    if (!otherProps.disabled) onClick(dateObject);
2 line

2019-09-17 05:45 UTC, ddalpange commented on src/formInputs/DatePicker/MonthCalendar/Day/index.tsx
> +    onHover && onHover(dateObject);
if를 써주십시옹. 이렇게 &&를 계속 붙이다 보면 의도치 않은 동작이 일어나기 쉽고 디버깅이 힘듬

2019-09-17 05:45 UTC, ddalpange commented on src/formInputs/DatePicker/MonthCalendar/index.tsx
> +    if (days.length % 7 > 0) days.push(...this.createDays(1, 7 - (days.length % 7) + 1, nowYear, nowMonth + 1, true));
두줄을 써주세용

2019-09-17 05:45 UTC, ddalpange commented on src/formInputs/DatePicker/MonthCalendar/index.tsx
> +        ...this.createDays(prevMonthLastDay - firstDayIndex + 1, prevMonthLastDay + 1, nowYear, nowMonth - 1, true)
push가 계속 반복되는데 
prevMonthOverDays, currentMonthDays, nextMonthBeforeDays 이런식으로 변수를 각각 써준 후 마지막에 concat을 해서 리턴하는건 어때?

2019-09-17 05:45 UTC, ddalpange commented on src/formInputs/DatePicker/index.tsx
> +  readonly onRangeChange?: (startDate: Date, endDate: Date) => boolean | void;
```suggestion
  readonly onRangeChange?: (dateRange: DateRange) => boolean | void;
```
이런식으로 받는 value와 emit하는 이벤트의 value의 형식을 통일해줘

2019-09-17 05:45 UTC, ddalpange commented on src/formInputs/DatePicker/index.tsx
> +    document.addEventListener('mousedown', this.handleClickOutside);
이거는 ssr때문에 미리 체크해줘야할거같담

2019-09-17 05:45 UTC, ddalpange commented on src/formInputs/DatePicker/index.tsx
> +    document.removeEventListener('mousedown', this.handleClickOutside);
이거는 ssr때문에 미리 체크해줘야할거같담

2019-09-17 05:45 UTC, ddalpange commented on src/formInputs/DatePicker/index.tsx
> +  private onInputBlur = () => {
얘는 받아서 처리하는 애니까 handle로 해줘!

2019-09-17 05:45 UTC, ddalpange commented on src/formInputs/DatePicker/index.tsx
> +  private onIncreaseBtnClick = () => {
얘는 받아서 처리하는 애니까 handle로 해줘!

2019-09-17 05:45 UTC, ddalpange commented on src/formInputs/DatePicker/index.tsx
> +  private onDecreaseBtnClick = () => {
얘는 받아서 처리하는 애니까 handle로 해줘!

2019-09-17 05:45 UTC, ddalpange commented on src/formInputs/DatePicker/index.tsx
> +  private onDateChanged = (date: Date) => {
얘는 받아서 처리하는 애니까 handle로 해줘!

2019-09-17 05:57 UTC, chiabi requested changes

2019-09-17 05:57 UTC, chiabi commented on src/formInputs/DatePicker/locales/ko_KR.ts
> +import lodash from 'lodash';
```suggestion
import { map } from 'lodash';
```
필요한 함수만 임포트해주세요

2019-09-17 05:57 UTC, chiabi commented on src/formInputs/DatePicker/MonthCalendar/index.tsx
> +  readonly max: Date | undefined;
minDate, maxDate 로 이름지어주는게 어떨까요?

2019-09-17 05:57 UTC, chiabi commented on src/formInputs/DatePicker/MonthCalendar/index.tsx
> +import lodash from 'lodash';
사용한 함수만 import해주세요

2019-09-17 05:57 UTC, chiabi commented on src/formInputs/DatePicker/MonthSelector/Month/index.tsx
> +    if (props.isSelected) return white;
```suggestion
    if (props.isSelected) {
       return white
    }
```
요런 코드 스타일 맞춰주세요

2019-09-17 05:57 UTC, chiabi commented on src/formInputs/DatePicker/index.tsx
> +    else if (selectorType === 'day') currentMonth.setMonth(currentMonth.getMonth() + 1);
if문은 한줄이어도 블록으로 감싸서 사용해주세요

2019-09-17 05:57 UTC, chiabi commented on src/formInputs/DatePicker/index.tsx
> +    else if (selectorType === 'day') currentMonth.setMonth(currentMonth.getMonth() - 1);
상동

2019-09-17 06:52 UTC, tbvjaos510 commented on src/formInputs/DatePicker/index.tsx
> +    document.addEventListener('mousedown', this.handleClickOutside);
ssr때 componentDidMount는 실행 안하지 않아?

2019-09-17 06:53 UTC, tbvjaos510 commented on src/formInputs/DatePicker/index.tsx
> +    document.addEventListener('mousedown', this.handleClickOutside);
일단 검사는 추가할게

2019-09-17 06:53 UTC, tbvjaos510 commented on src/formInputs/DatePicker/index.tsx
> +    document.removeEventListener('mousedown', this.handleClickOutside);
위랑 똑같긴한데 수정은 하겠습니당

2019-09-17 06:56 UTC, tbvjaos510 commented on src/formInputs/DatePicker/MonthCalendar/Day/index.tsx
> +    if (!otherProps.disabled) onClick(dateObject);
수정 완료

2019-09-17 06:56 UTC, tbvjaos510 commented on src/formInputs/DatePicker/MonthCalendar/Day/index.tsx
> +    onHover && onHover(dateObject);
수정 완료

2019-09-17 06:56 UTC, tbvjaos510 commented on src/formInputs/DatePicker/MonthCalendar/index.tsx
> +    if (days.length % 7 > 0) days.push(...this.createDays(1, 7 - (days.length % 7) + 1, nowYear, nowMonth + 1, true));
수정 완료

2019-09-17 07:26 UTC, tbvjaos510 commented on src/formInputs/DatePicker/MonthCalendar/index.tsx
> +        ...this.createDays(prevMonthLastDay - firstDayIndex + 1, prevMonthLastDay + 1, nowYear, nowMonth - 1, true)
다음 달을 계산할 때 기존에 계산된 값이 필요해서 하나로 합쳐야 할 것 같아.. 3개로 나누기에는 오히려 뒤에 코드가 복잡해져서 놔둬야 할듯!

2019-09-17 07:26 UTC, tbvjaos510 commented on src/formInputs/DatePicker/index.tsx
> +  readonly onRangeChange?: (startDate: Date, endDate: Date) => boolean | void;
수정 완료

2019-09-17 07:26 UTC, tbvjaos510 commented on src/formInputs/DatePicker/index.tsx
> +  private onInputBlur = () => {
수정 완료

2019-09-17 07:26 UTC, tbvjaos510 commented on src/formInputs/DatePicker/index.tsx
> +  private onIncreaseBtnClick = () => {
수정 완료

2019-09-17 07:26 UTC, tbvjaos510 commented on src/formInputs/DatePicker/locales/ko_KR.ts
> +import lodash from 'lodash';
수정 완료

2019-09-17 07:26 UTC, tbvjaos510 commented on src/formInputs/DatePicker/MonthCalendar/index.tsx
> +import lodash from 'lodash';
수정 완료

2019-09-17 07:27 UTC, tbvjaos510 commented on src/formInputs/DatePicker/MonthCalendar/index.tsx
> +  readonly max: Date | undefined;
수정 완료

2019-09-17 07:28 UTC, tbvjaos510 commented
수정 완료하였습니다~~

2019-09-17 07:58 UTC, ddalpange requested changes

2019-09-17 07:58 UTC, ddalpange commented on src/formInputs/DatePicker/index.tsx
> +  readonly onRangeChange?: (dateRange: DateRange) => boolean | void;
```suggestion
  readonly onChangeRange?: (dateRange: DateRange) => boolean | void;
```

2019-09-17 07:58 UTC, ddalpange commented on src/formInputs/DatePicker/index.tsx
> +        <Picker position={alwaysShow ? 'static' : 'absolute'} visible={alwaysShow || modalVisible} ref={this.modalRef}>
alwaysShow, modalVisible를 받아서 styled 안에서 계산하장

2019-09-17 07:58 UTC, ddalpange commented on src/formInputs/DatePicker/index.tsx
> +    if (document) {
이거 윈도우 체크 안해도 되려나?

2019-09-18 04:08 UTC, tbvjaos510 commented on src/formInputs/DatePicker/index.tsx
> +    if (document) {
윈도우 체크하는거를 실수가 많이 생겨서 utils로 분리했어

2019-09-19 03:38 UTC, tbvjaos510 commented
코멘트를 잊었넹. 수정완료했습니다.
* document를 확인하는 로직을 사용하는 부분이 많아서 util에 별도로 분리하였습니다. (isServer, isClient)
  그에맞게 document를 확인하는 부분을 전부 함수로 치환하였습니다.

2019-09-19 05:37 UTC, chiabi approved these changes

2019-09-19 06:46 UTC, ddalpange approved these changes

2019-09-19 06:47 UTC, merged