feat: Checkbox 추가
pedaling/class101-ui pull request #9
Opened 2019-01-14 04:41 UTC by EsmondCho

2019-01-14 05:06 UTC, bae-unidev requested changes

2019-01-14 05:06 UTC, bae-unidev commented on src/Checkbox/index.tsx
> +  style?: {};
React.CSSProperties 타입으로 설정해주세요.

2019-01-14 05:06 UTC, bae-unidev commented on src/Checkbox/index.tsx
> +  inputStyle?: {};
React.CSSProperties 타입으로 설정해주세요

2019-01-14 05:06 UTC, bae-unidev commented on src/Checkbox/index.tsx
> +const Container = styled.div<Props>`
label로 해주세요...

2019-01-14 06:47 UTC, sim-zi requested changes

2019-01-14 06:47 UTC, cheolee commented on docs/components/Checkbox.tsx
> +// @flow
flow 제거해주세욥

2019-01-14 06:47 UTC, cheolee commented on src/Checkbox/index.tsx
> +// @flow
flow

2019-01-14 06:47 UTC, cheolee commented on src/Checkbox/index.tsx
> +  public readonly state: State = {
state에 타입 지정해주지 않아도 됨!

2019-01-14 06:47 UTC, cheolee commented on src/Checkbox/index.tsx
> +        checked: props.checked,
props와 state 모두에 checked를 가지고 있는 건 이상하다.

대부분의 상황에서 되도록이면 controlled-components 이기를 권장하는데, state를 제거할 수 있으면 제거해보장.

혹시 redux-form 때문인가 싶어서 찾아보니 controlled도 지원하는 것 같넹
https://redux-form.com/6.0.0-alpha.4/docs/api/field.md/

의도가 있는 게 아니라면 input 종류는 아래 두 가지 패턴 중 하나로 구현하는 게 좋겠음! (controlled 권장)
https://reactjs.org/docs/forms.html#controlled-components
https://reactjs.org/docs/uncontrolled-components

2019-01-14 06:47 UTC, cheolee commented on src/Checkbox/index.tsx
> +  allowMessage?: string;
allowMessage가 동사로 시작해서 함수 느낌이 난다. 명사형으로 고쳐보자

2019-01-14 06:47 UTC, cheolee commented on src/Checkbox/index.tsx
> +      <div style={style}>
className을 가져왔는데, 사용하지 않고 있다.
아마도 이 엘리먼트에 주입하려고 한 거겠징??

안 쓰는 변수는 PR 만들기 전에 꼭 지워주면 좋겠음!

2019-01-14 06:47 UTC, cheolee commented on docs/components/Checkbox.tsx
> +export const Component = ({
@chiabi @iseongho 다른 컴포넌트들도 이런 파일이 있던데, 요건 어떤 의도로 존재하는 거야?
요렇게 컴포넌트를 감싸면 Playground에 보이는 예제가 실제 사용례랑 달라질 수 있을 것 같은뎅..!

2019-01-14 06:47 UTC, cheolee commented on docs/components/Checkbox.tsx
> +export interface Props {
이거 Checkbox의 Props를 두고 따로 만든 이유가 있을까?
HTMLInputProps 을 모두 사용하면 안 되는 상황인감?

2019-01-14 06:59 UTC, sim-zi requested changes

2019-01-14 06:59 UTC, cheolee commented on src/Checkbox/index.tsx
> +const ErrorText = styled.h6`
ErrorText, WarnText, AllowText가 스타일이 동일하고 color만 다른 것 같은데, 하나의 컴포넌트를 사용하고 color를 prop으로 받게 리팩토링하자

2019-01-14 06:59 UTC, cheolee commented on src/Checkbox/index.tsx
> +const ErrorText = styled.h6`
그러면 96~107 라인을 세 가지 분기로 나눌 필요 없이 간결하게 쓸 수 있을 듯

2019-01-14 06:59 UTC, cheolee commented on src/Checkbox/index.tsx
> +const DescriptionIcon = styled.img.attrs({ alt: '!' })`
이거 SVG 아이콘 컴포넌트는 따로 없는거야?
되도록이면 svg로 쓰면 좋겠는뎅!

2019-01-14 07:10 UTC, bae-unidev commented on docs/components/Checkbox.tsx
> +export interface Props {
ㅇㅇ 이 파일의 Props는 docz 문서에 보여지는 용도로 만든거라, HTMLInputProps를 확장하면 PropsTable에 다 보이지 않음?

2019-01-14 08:38 UTC, cheolee commented on docs/components/Checkbox.tsx
> +export interface Props {
그렇긴 하징..!
근데 그러면 결국 예제에 사용한 props 말고는 전체 props를 다 못 보여줄 거 같은디..!
그리고 같은 타입인데 타입 선언도 둘로 쪼개지니까 매번 props 작업 할 때마다 두 번 써야하구

그래서 토스에서 만들 땐 이렇게 prop 하나 만들어서 거기다가 HTMLInputProps 같은 거 넣었음
<img width="925" alt="2019-01-14 5 36 48" src="https://user-images.githubusercontent.com/5275823/51102636-1cf12b00-1823-11e9-8d69-f7dfbad82141.png">

2019-01-14 10:08 UTC, bae-unidev commented on docs/components/Checkbox.tsx
> +export const Component = ({
이게 아마 docz에 styled-component랑 같이 쓰면 생기는 이슈가 있었는데, 그거 때문일듯?

2019-01-14 10:08 UTC, bae-unidev commented on docs/components/Checkbox.tsx
> +export interface Props {
방금 확인해봤는데 타입 상속받아 써도 PropsTable에 안나온다!

2019-01-14 11:20 UTC, EsmondCho commented on docs/components/Checkbox.tsx
> +export interface Props {
그러면 어떻게 바꾸면 되는거야?

2019-01-15 06:21 UTC, EsmondCho commented on src/Checkbox/index.tsx
> +        checked: props.checked,
그런데 이해가 잘 안되는게, 지금 이것도 controlled-components인거 아니야? state가 없어지면 controlled-components가 user-input에 맞게 값을 저장을 못하는거 아닌가

2019-01-15 13:26 UTC, sim-zi commented on docs/components/Checkbox.tsx
> +export interface Props extends HTMLInputProps {
이거 이렇게 할 거라면
https://github.com/pedaling/class101-ui/pull/9/files#diff-a76049c264afe279d372022dfd724e3aR8

이거랑 똑같은 거 같은데, 하나로 씁시당

근데 class101-ui 개발하시는 분들 의견을 들어봐야할듯
이렇게하면 docz에 prop table이 길게 나오는 문제가 있어가지고 여기서 보여줄 것만 썼던 것 같은디

2019-01-15 13:26 UTC, sim-zi commented on docs/components/Checkbox.tsx
> +export class MyCheckbox extends React.Component {
class101-ui 개발자 분들께 질문...
이걸 이렇게 감싸서 Playground에 보여주면 실제 사용례랑 너무 달라지는 것 같은디 어떻게 생각함니까!
이런 코드들까지 Playground에 포함되어야 할 것 같다..!

2019-01-15 13:26 UTC, sim-zi commented on src/Checkbox/index.tsx
> +const StyledCheckbox = styled.input.attrs({ type: 'checkbox' })`
Styled~~ 라고 이름 짓기보다는 어떤 스타일이 입혀졌는지 알 수 있는 이름이 좋겠당

`HiddenCheckbox` 같은 느낌..?

2019-01-15 13:26 UTC, sim-zi commented on src/Checkbox/index.tsx
> +  ${DescriptionStyle};
DescriptionStyle을 inline으로 쓰자

2019-01-15 13:26 UTC, sim-zi commented on src/Checkbox/index.tsx
> +  readonly color: string;
찾아보니 props에는 readonly를 안 써도 된다고 합니다..!!

2019-01-15 13:26 UTC, sim-zi commented on src/Checkbox/index.tsx
> +        {allowingMessage && !errorMessage && <MessageText color={gray600}>{allowingMessage}</MessageText>}
74~86 라인에 비슷한 jsx가 세 번 반복되는데, 하나로 합치면 좋을 것 같아

status는 'allowing', 'error', 'warning' 세 가지고, 각각 
```
{
  message: string,
  textColor: string,
  descriptionIconColor?: string, // 존재하면 아이콘 표시
}
```
이런 값을 가져서

2019-01-15 13:52 UTC, cheolee commented on src/Checkbox/index.tsx
> +      <div style={style}>
className 주입해주도록 합시다!

2019-01-15 13:52 UTC, cheolee commented on src/interfaces/props.ts
> +export interface HTMLInputProps extends React.InputHTMLAttributes<HTMLInputElement> {}
이게 필요할까? React.InputHTMLAttributes<HTMLInputElement> 라고 그대로 써주는 편이 React 개발자한테 익숙할 것 같아

2019-01-16 03:49 UTC, bae-unidev commented
이거 일단 build 고쳐주라!

```
12:04:05 AM: $ tsc -p . && rollup -c
12:04:12 AM: src/Checkbox/index.tsx(6,23): error TS2307: Cannot find module '@class101/ui/Icon'.
12:04:12 AM: src/Checkbox/message.tsx(3,23): error TS2307: Cannot find module '@class101/ui/Icon'.
12:04:12 AM: error Command failed with exit code 1.
```

2019-01-16 03:54 UTC, EsmondCho commented on docs/components/Checkbox.tsx
> +export class MyCheckbox extends React.Component {
onChange, value를 필수로 가지게 바꾸기

2019-01-16 07:40 UTC, bae-unidev approved these changes

2019-01-17 02:40 UTC, bae-unidev commented
PropTable이 안보이는데 이거 고쳐주라!

2019-01-17 06:56 UTC, EsmondCho commented
이거 내가 머지하면됌??

2019-01-17 07:07 UTC, merged