feat: SwitchButton 추가
pedaling/class101-ui pull request #91
Opened 2019-08-21 06:44 UTC by tbvjaos510

SwitchButton을 FormInput 하위 디렉토리에 추가.

## Image
![image](https://user-images.githubusercontent.com/32216112/63408175-6775fe00-c429-11e9-83f1-34f91609a083.png)

2019-08-21 06:46 UTC, tbvjaos510 commented on src/index.ts
> +export * from './FormInput';
FormInput에 항목을 한번에 export할 수 있게 했는데, FormInput폴더에 있는 것도 components폴더로 옮길 예정임?

2019-08-21 07:58 UTC, chiabi commented on src/FormInput/SwitchButton/index.tsx
> +import * as Colors from '../../Colors';
이렇게 가져오면 트리셰이킹이 되나요?

2019-08-21 07:58 UTC, chiabi commented on src/FormInput/SwitchButton/index.tsx
> +    checked: undefined,
없으면 undefined인데 옵셔널로 안하고 defaultProps에 정의한 이유가 있나요?

2019-08-21 07:58 UTC, chiabi commented on src/FormInput/SwitchButton/index.tsx
> +const transitionAnimation = '0.25s ease-out 0.10s';
애니메이션이 좀 느려 보이는데 쿤이랑 같이 봐줘

2019-08-21 07:58 UTC, chiabi commented on src/FormInput/SwitchButton/index.tsx
> +  font-size: 1em;
em단위를 쓰고 있지 않은데 em을 쓴 이유가 있나요?

2019-08-21 07:59 UTC, chiabi commented on src/index.ts
> +export * from './FormInput';
@bae-unidev 요 주석의 의미는 formInput도 포함한 거야?

2019-08-21 08:04 UTC, chiabi commented on src/FormInput/SwitchButton/index.tsx
> +const transitionAnimation = '0.25s ease-out 0.10s';
스위치 버튼에 cursor: pointer 도 추가해주세용

2019-08-21 08:55 UTC, tbvjaos510 commented on src/FormInput/SwitchButton/index.tsx
> +import * as Colors from '../../Colors';
수정완료!

2019-08-21 08:56 UTC, tbvjaos510 commented on src/FormInput/SwitchButton/index.tsx
> +    checked: undefined,
수정완료!

2019-08-21 09:23 UTC, tbvjaos510 commented on src/FormInput/SwitchButton/index.tsx
> +  font-size: 1em;
처음 테스트할때 텍스트때매 추가하고 삭제를 깜빡한 듯. 삭제완료!

2019-08-21 09:24 UTC, tbvjaos510 commented on src/FormInput/SwitchButton/index.tsx
> +const transitionAnimation = '0.25s ease-out 0.10s';
cursor는 추가했고 애니메이션 속도는 조금 빠르게 늘렸당

2019-08-21 09:26 UTC, tbvjaos510 commented
쿤이랑 상의해서 Switch로 이름 변경하고 size를 삭제하고 일부 색 변경했어. 참고해줘

2019-08-21 10:29 UTC, chiabi commented on src/FormInput/Switch/index.tsx
> +    cursor: pointer;
disabled 일때는 not-allowed로 넣어주세요

2019-08-21 10:42 UTC, chiabi requested changes

2019-08-21 10:42 UTC, chiabi commented on src/FormInput/Switch/index.tsx
> +const switcherStyleBySize = css`
size가 없어서 BySize말고 다른 이름으 주는 게 좋을 것 같아요

2019-08-21 11:18 UTC, tbvjaos510 commented on src/FormInput/Switch/index.tsx
> +const switcherStyleBySize = css`
아 오케이. 쿤이 디자인 바꿔서 낼 수정하겠습니당

2019-08-22 06:41 UTC, tbvjaos510 commented on src/FormInput/Switch/index.tsx
> +    cursor: pointer;
수정완료!

2019-08-22 06:43 UTC, tbvjaos510 commented
![image](https://user-images.githubusercontent.com/32216112/63491935-6c06e900-c4f3-11e9-89c5-79c9fda0b93b.png)

* Text 와 함께 쓸 수 있도록 수정.
* hover상태일 때 background color 추가

2019-08-22 06:45 UTC, tbvjaos510 commented on src/FormInput/Switch/index.tsx
> +  offText?: React.ReactNode;
props에 onText, offText 이름 이렇게 해도 되겠지?

2019-08-22 07:21 UTC, chiabi commented on src/FormInput/Switch/index.tsx
> +  offText?: React.ReactNode;
onText랑 offText는 항상 같이 쓰여야하는 거야?

2019-08-22 07:31 UTC, chiabi commented on src/FormInput/Switch/index.tsx
> +  offText?: React.ReactNode;
같이 쓰여야하는 거면 요거만 문서에 명시해주자

2019-08-22 07:33 UTC, tbvjaos510 commented on src/FormInput/Switch/index.tsx
> +  offText?: React.ReactNode;
코드 상에는 하나만 써도 텍스트 나타나게 했는데 같이 쓰이게 만들까?

2019-08-22 07:45 UTC, chiabi approved these changes

2019-08-22 08:14 UTC, chiabi commented on src/FormInput/Switch/index.tsx
> +            {children || (checked ? onText : offText)}
onText랑 offText 둘 중 하나만 쓰면  checked 상태에따라 아무것도 안 나올 수 있지 않아?

2019-08-22 08:48 UTC, tbvjaos510 commented on src/FormInput/Switch/index.tsx
> +            {children || (checked ? onText : offText)}
체크가 됐을때만 나타나는 텍스트나 컴포넌트도 있지 않을까? 너무 어렵게 생각했나..

2019-08-22 09:15 UTC, bae-unidev reviewed
이거 컴포넌트 이름 Switch로 바꿔주라!

2019-08-22 09:15 UTC, bae-unidev commented on src/index.ts
> +export * from './FormInput';
ㅇㅇ 모든 컴포넌트들 components로 옮겨야할 것 같애서

2019-08-22 10:01 UTC, tbvjaos510 commented
@bae-unidev  지금 컴포넌트 명이 Switch인데 FormInput에서 Component안으로 옮기면 돼??

2019-08-23 07:03 UTC, tbvjaos510 commented
* Switch를 Component폴더로 옮김
* `onText`와 `offText` 둘 다 적어야 텍스트가 나타나게 수정
* 문서에도 둘 다 사용하라고 명시
* forminput폴더에서 components폴더로 옮김

2019-08-23 12:53 UTC, merged