feat: Add Modal BottomSheet
pedaling/class101-ui pull request #98
Opened 2019-08-27 08:24 UTC by tbvjaos510

ModalBottomSheet를 만들었습니다.

## Image

### PC
![image](https://user-images.githubusercontent.com/32216112/63753690-88899380-c8ee-11e9-8d11-99f3c15cc34b.png)

### Mobile
![image](https://user-images.githubusercontent.com/32216112/63754196-6a706300-c8ef-11e9-9801-14b44ce4f9e4.png)

2019-08-27 08:42 UTC, ddalpange requested changes

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  open: boolean;
```suggestion
  opened: boolean;
```

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  okText?: string;
successText

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  okColor: ContainButtonColorValue;
successColor

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  mounted: boolean;
```suggestion
  ssr: boolean;
```

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  onOk?: (close: () => void) => void;
```suggestion
  onSuccess?: (close: () => void) => void;
```

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  componentWillUnmount() {
```suggestion
public  componentWillUnmount() {
```

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  componentDidMount() {
```suggestion
public  componentDidMount() {
```

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  private disableBodyScroll = () => {
이거 이 방법밖에 없나?
SSR이 안될 것 같은데

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  open: boolean;
```suggestion
  opened: boolean;
```

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  private notifyModalClose = () => {
```suggestion
  private handleCloseModal = () => {
```

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  private notifyModalCancel = () => {
```suggestion
  private handleCancelModal = () => {
```

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +    if (!mounted) return opener || null;
두줄

2019-08-27 08:42 UTC, ddalpange commented on src/components/ModalBottomSheet/index.tsx
> +  static getDerivedStateFromProps(nextProps: Props, prevState: State): Partial<State> | null {
안쓰면 지우자

2019-08-27 11:02 UTC, chiabi commented
충돌 해결해 주세용
그리고 모달에 컨텐츠 양 옆으로 꽉차게도 넣을 수 있어?

2019-08-28 01:47 UTC, tbvjaos510 commented on src/components/ModalBottomSheet/index.tsx
> +  mounted: boolean;
얘는 mounted를 설정하면 ssr 작동이 안되는거라서 `noSsr`로 하겠습니당

2019-08-28 01:51 UTC, tbvjaos510 commented on src/components/ModalBottomSheet/index.tsx
> +  static getDerivedStateFromProps(nextProps: Props, prevState: State): Partial<State> | null {
아 console.log를 안지웠구나 props를 state로 넘겨야해서 써야할듯

2019-08-28 01:54 UTC, tbvjaos510 commented on src/components/ModalBottomSheet/index.tsx
> +  private disableBodyScroll = () => {
componentDIdUpdate에서 실행해서 ssr에선 실행 안될거야

2019-08-28 02:10 UTC, tbvjaos510 commented
@chiabi 모달에 좌우 패딩을 삭제하라는 뜻이지??

2019-08-28 03:06 UTC, chiabi commented
좌우 패딩은 있어야하는데 콘텐츠에 마이너스 마진을 넣으면 양 옆으로 꽉차게 들어갈 수 있는지 물어본 거였음!

2019-08-28 04:36 UTC, tbvjaos510 commented on src/components/ModalBottomSheet/index.tsx
> +    if (!mounted) return opener || null;
중괄호넣어서 두줄로 하라는거지??

2019-08-28 05:04 UTC, tbvjaos510 commented
`contentStyle`, `modalStyle`로 스타일 오버라이드 할 수 있게 했고 `removeContentPadding` props 추가했당

2019-08-28 05:06 UTC, tbvjaos510 commented
수정 완료했습니다.

2019-08-28 06:27 UTC, chiabi commented on src/overlays/ModalBottomSheet/index.tsx
> +  overflow-y: scroll;
showScroll이 기본적으로 false이고 
이 스크롤이 안될 수도 있는 경우를 설정한 이유가 있을까?
만약 요소가 넘었을때만 스크롤 바를 넣고 싶다면 overflow-y: auto를 주면 될 것 같은데

2019-08-28 07:05 UTC, tbvjaos510 commented on src/overlays/ModalBottomSheet/index.tsx
> +  overflow-y: scroll;
아 항상 스크롤이 넘었을때만 showScroll을 테스트해서 scroll로 설정된걸 의식을 못했었다. 지금 수정할게 감사합니당.

2019-08-28 08:44 UTC, chiabi commented on src/overlays/ModalBottomSheet/index.tsx
> +    !props.showScroll &&
이거 scrollbar 보이는 거만 제어하는 props면 없애고 
모바일에서 

&::-webkit-scrollbar {
      display: none;
    } 스타일 넣어주자

2019-08-28 10:54 UTC, tbvjaos510 commented
수정했습니당

2019-08-28 11:26 UTC, chiabi approved these changes

2019-08-29 03:44 UTC, tbvjaos510 commented
rebase를 못하고 충돌 해결할 때 merge로 했네... 다음부터 rebase하겠습니당..

2019-08-29 03:45 UTC, merged